### Import Dependencies

In [1]:
import openai
import pandas as pd

from qdrant_client import QdrantClient
from qdrant_client import models
from qdrant_client.models import VectorParams, Distance, SparseVectorParams, Modifier, PayloadSchemaType, PointStruct, Document, Prefetch, FusionQuery

### Create Qdrant collection for hybrid search

In [2]:
qdrant_client = QdrantClient(url="http://localhost:6333")

In [4]:
qdrant_client.create_collection(
    collection_name="Amazon-items-collection-01-hybrid-search",
    vectors_config={
        "text-embedding-3-small": VectorParams(size=1536, distance=Distance.COSINE)
    },
    sparse_vectors_config={
        "bm25": SparseVectorParams(modifier=Modifier.IDF)
    }
)

True

In [5]:
qdrant_client.create_payload_index(
    collection_name="Amazon-items-collection-01-hybrid-search",
    field_name="parent_asin",
    field_schema=PayloadSchemaType.KEYWORD
)

UpdateResult(operation_id=2, status=<UpdateStatus.COMPLETED: 'completed'>)

### Embedding Functions

In [6]:
def get_embedding(text, model="text-embedding-3-small"):
    response = openai.embeddings.create(
        input=text,
        model=model
    )
    return response.data[0].embedding

In [7]:
def get_embeddings_batch(text_list, model="text-embedding-3-small", batch_size=100):
    
    if len(text_list) <= batch_size:
        response = openai.embeddings.create(input=text_list, model=model)
        return [embedding.embedding for embedding in response.data]
    
    all_embeddings = []
    counter = 1
    for i in range(0, len(text_list), batch_size):
        batch = text_list[i:i + batch_size]
        response = openai.embeddings.create(input=batch, model=model)
        all_embeddings.extend([embedding.embedding for embedding in response.data])
        print(f"Processed {counter * batch_size} of {len(text_list)}")
        counter += 1
    
    return all_embeddings

### Read the sampled dataset with Amazon inventory data

In [8]:
df_items = pd.read_json("../../data/meta_Electronics_2022_2023_with_category_ratings_100_sample_1000.jsonl", lines=True)

In [9]:
df_items.head()

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author
0,AMAZON FASHION,"Bosttor Bluetooth Beanie Hat with Light, Headl...",4.5,2342,"[100% Acrylic, Elastic closure, Hand Wash Only...",[],26.99,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Beanie Hat with Bluetooth Headphon...,Bosttor,"[Electronics, Headphones, Earbuds & Accessorie...","{'Department': 'unisex-adult', 'Date First Ava...",B0BH41HYFZ,NaN,NaN,NaN
1,All Electronics,"Aceele USB and USB C to Ethernet Adapter, 3.3f...",4.2,148,[【USB or USB C to Ethernet Adapter】The Etherne...,[],14.99,[{'thumb': 'https://m.media-amazon.com/images/...,[],Aceele,"[Electronics, Computers & Accessories, Network...",{'Product Dimensions': '3.54 x 0.98 x 0.71 inc...,B0BKPB2YQ9,NaN,NaN,NaN
2,All Electronics,HDMI Switch 3 in 1 Out 4K UHD HDMI Switcher Sp...,4.2,3331,[📍3-Port HDMI Switch: This aluminum HDMI switc...,[],18.98,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Darren reviews VWRHAR 3-1 splitter...,VWRHar,"[Electronics, Home Audio, Home Audio Accessori...",{'Package Dimensions': '6.1 x 4.21 x 0.94 inch...,B09MM5QT3R,NaN,NaN,NaN
3,All Electronics,"Smart Watch,Ip67 Waterproof Bluetooth Smartwat...",3.4,125,[],[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],Burxoe,[],{'Package Dimensions': '3.15 x 3.07 x 2.52 inc...,B09Q5TNDHY,NaN,NaN,NaN
4,Cell Phones & Accessories,"(3 Pack) Cute Airpod Case for Airpods 2&1,3D D...",4.7,335,[【Compatible Airpods 1/2 】This case designed f...,[1],11.99,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'airpod cases', 'url': 'https://www...",UGUHY,"[Electronics, Headphones, Earbuds & Accessorie...",{'Package Dimensions': '7.44 x 4.61 x 1.57 inc...,B0BZJKX7MS,NaN,NaN,NaN

### Preprocess title and features

In [11]:
def preprocess_description(row):
    return f"{row['title']} {' '.join(row['features'])}"

In [12]:
def extract_first_large_image(row):
    return row["images"][0].get("large", "")

In [13]:
df_items["preprocessed_description"] = df_items.apply(preprocess_description, axis=1)
df_items["image"] = df_items.apply(extract_first_large_image, axis=1)

In [14]:
df_items.head()

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author,preprocessed_description,image
0,AMAZON FASHION,"Bosttor Bluetooth Beanie Hat with Light, Headl...",4.5,2342,"[100% Acrylic, Elastic closure, Hand Wash Only...",[],26.99,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Beanie Hat with Bluetooth Headphon...,Bosttor,"[Electronics, Headphones, Earbuds & Accessorie...","{'Department': 'unisex-adult', 'Date First Ava...",B0BH41HYFZ,NaN,NaN,NaN,"Bosttor Bluetooth Beanie Hat with Light, Headl...",https://m.media-amazon.com/images/I/51b7qcj8dZ...
1,All Electronics,"Aceele USB and USB C to Ethernet Adapter, 3.3f...",4.2,148,[【USB or USB C to Ethernet Adapter】The Etherne...,[],14.99,[{'thumb': 'https://m.media-amazon.com/images/...,[],Aceele,"[Electronics, Computers & Accessories, Network...",{'Product Dimensions': '3.54 x 0.98 x 0.71 inc...,B0BKPB2YQ9,NaN,NaN,NaN,"Aceele USB and USB C to Ethernet Adapter, 3.3f...",https://m.media-amazon.com/images/I/41WsGRr-3T...
2,All Electronics,HDMI Switch 3 in 1 Out 4K UHD HDMI Switcher Sp...,4.2,3331,[📍3-Port HDMI Switch: This aluminum HDMI switc...,[],18.98,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Darren reviews VWRHAR 3-1 splitter...,VWRHar,"[Electronics, Home Audio, Home Audio Accessori...",{'Package Dimensions': '6.1 x 4.21 x 0.94 inch...,B09MM5QT3R,NaN,NaN,NaN,HDMI Switch 3 in 1 Out 4K UHD HDMI Switcher Sp...,https://m.media-amazon.com/images/I/41fsjaknf1...
3,All Electronics,"Smart Watch,Ip67 Waterproof Bluetooth Smartwat...",3.4,125,[],[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],Burxoe,[],{'Package Dimensions': '3.15 x 3.07 x 2.52 inc...,B09Q5TNDHY,NaN,NaN,NaN,"Smart Watch,Ip67 Waterproof Bluetooth Smartwat...",https://m.media-amazon.com/images/I/51YFypeuZh...
4,Cell Phones & Accessories,"(3 Pack) Cute Airpod Case for Airpods 2&1,3D D...",4.7,335,[【Compatible Airpods 1/2 】This case designed f...,[1],11.99,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'airpod cases', 'url': 'https://www...",UGUHY,"[Electronics, Headphones, Earbuds & Accessorie...",{'Package Dimensions': '7.44 x 4.61 x 1.57 inc...,B0BZJKX7MS,NaN,NaN,NaN,"(3 Pack) Cute Airpod Case for Airpods 2&1,3D D...",https://m.media-amazon.com/images/I/41V7Wi2ckb...

In [15]:
list(df_items["preprocessed_description"].items())[0]

(0,
 'Bosttor Bluetooth Beanie Hat with Light, Headlamp Cap with Headphones and Built-in Speaker Mic, Gifts for Men Women Teen 100% Acrylic Elastic closure Hand Wash Only 【Upgraded Bluetooth Beanie】Bosttor upgraded Bluetooth wireless technology offer much stable and strong connection, support music and calling, easy and fast to pair with your devices. Maximum transmission distance up to 33 feet. Built-in Stereo Speakers & Mic, enhance your music listening experience. 【Long Working Time Music Hat】Built with easy-access USB charging port, simply charge it via the included USD cable. It takes 1-2 hours to get full charged. The battery offers continuous working hours up to 10 hours. Perfect for camping, hiking, skiing, hunting, jogging, cycling, dog walking, auto repair, etc. 【LED Headlight Light Up Your Way】Hands-free LED light is rechargeable and removable. You can remove it to charge by laptop, power bank, socket, car charger, etc. The 4 LED lights can light up to 30 feet away. It points directional light toward what your eyes are looking at. It has 3 brightness settings. 【One Size Fits Most】Bosttor unisex beanie hat is made from the ultra-soft acrylic blend material that provides excellent insulation against cold winter air. Elastic and comfortable LED hat fits men women and teens. It is hand washable, please remove the LED and the headset before washing. 【Ideal Birthday & Christmas Gifts】Our beanie hat with Bluetooth and LED headlight is the ideal gift for runners and outdoor adventurers in winter. It is also your best gift choice for men women and teenagers. This is the perfect gift for anyone in the family and your friends. Your Ideal choice for Thanksgiving Day, Christmas, Birthday and Anniversary.')

In [16]:
list(df_items["image"].items())[0]

(0, 'https://m.media-amazon.com/images/I/51b7qcj8dZL._AC_.jpg')

In [17]:
df_data_to_embed = df_items[["preprocessed_description", "image", "rating_number", "price", "average_rating", "parent_asin"]]

In [18]:
df_data_to_embed.head()

,preprocessed_description,image,rating_number,price,average_rating,parent_asin
0,"Bosttor Bluetooth Beanie Hat with Light, Headl...",https://m.media-amazon.com/images/I/51b7qcj8dZ...,2342,26.99,4.5,B0BH41HYFZ
1,"Aceele USB and USB C to Ethernet Adapter, 3.3f...",https://m.media-amazon.com/images/I/41WsGRr-3T...,148,14.99,4.2,B0BKPB2YQ9
2,HDMI Switch 3 in 1 Out 4K UHD HDMI Switcher Sp...,https://m.media-amazon.com/images/I/41fsjaknf1...,3331,18.98,4.2,B09MM5QT3R
3,"Smart Watch,Ip67 Waterproof Bluetooth Smartwat...",https://m.media-amazon.com/images/I/51YFypeuZh...,125,NaN,3.4,B09Q5TNDHY
4,"(3 Pack) Cute Airpod Case for Airpods 2&1,3D D...",https://m.media-amazon.com/images/I/41V7Wi2ckb...,335,11.99,4.7,B0BZJKX7MS

In [19]:
data_to_embed = df_data_to_embed.to_dict(orient="records")

In [20]:
data_to_embed

[{'preprocessed_description': 'Bosttor Bluetooth Beanie Hat with Light, Headlamp Cap with Headphones and Built-in Speaker Mic, Gifts for Men Women Teen 100% Acrylic Elastic closure Hand Wash Only 【Upgraded Bluetooth Beanie】Bosttor upgraded Bluetooth wireless technology offer much stable and strong connection, support music and calling, easy and fast to pair with your devices. Maximum transmission distance up to 33 feet. Built-in Stereo Speakers & Mic, enhance your music listening experience. 【Long Working Time Music Hat】Built with easy-access USB charging port, simply charge it via the included USD cable. It takes 1-2 hours to get full charged. The battery offers continuous working hours up to 10 hours. Perfect for camping, hiking, skiing, hunting, jogging, cycling, dog walking, auto repair, etc. 【LED Headlight Light Up Your Way】Hands-free LED light is rechargeable and removable. You can remove it to charge by laptop, power bank, socket, car charger, etc. The 4 LED lights can light up to 30 feet away. It points directional light toward what your eyes are looking at. It has 3 brightness settings. 【One Size Fits Most】Bosttor unisex beanie hat is made from the ultra-soft acrylic blend material that provides excellent insulation against cold winter air. Elastic and comfortable LED hat fits men women and teens. It is hand washable, please remove the LED and the headset before washing. 【Ideal Birthday & Christmas Gifts】Our beanie hat with Bluetooth and LED headlight is the ideal gift for runners and outdoor adventurers in winter. It is also your best gift choice for men women and teenagers. This is the perfect gift for anyone in the family and your friends. Your Ideal choice for Thanksgiving Day, Christmas, Birthday and Anniversary.',
  'image': 'https://m.media-amazon.com/images/I/51b7qcj8dZL._AC_.jpg',
  'rating_number': 2342,
  'price': 26.99,
  'average_rating': 4.5,
  'parent_asin': 'B0BH41HYFZ'},
 {'preprocessed_description': 'Aceele USB and USB C to Ethernet Adapter, 3.3ft Long Cord,Aluminum 3 Ports USB 3.0 Hub with RJ45 10/100/1000 Gigabit Ethernet Adapter, RJ45+Gigabit LAN Network Adapter with USB C Adapter for Laptop 【USB or USB C to Ethernet Adapter】The Ethernet adapter comes with a USB C adapter which to connect to Ethernet whether the computer only USB C interface or USB A interface, also easily transform the type-C port on the device to 3 Type A ports, , allows you use network and other USB devices at the same time. 【Extra 3 USB 3.0 Ports】This Ethernet adapter offers extra 3ports USB 3.0 ports,USB port data transfer feed up to 5 Gbps speed, 10x faster than USB 2.0(480 Mbps). Faster transfer HD movie in seconds at blazing. ⛔Note: To ensure the best performance of this USB 3.0 hub, please do not use it for charging purposes, data transfer only. 【RJ45 Gigabit Ethernet Adapter】The usb c to ethernet adapter provides access to superfast network speed, up to 1000Mbps, backward compatible with 10Mbps / 100Mbps. It can provide a more stable connection than WiFi. Our ethernet adapter for laptop supports large downloads at maximum speeds without interruption. Is a perfect solution to buffer-free movie streaming, online gaming, data transferring, and video conferencing. (⛔To reach 1Gbps, make sure to use CAT6 & up Ethernet cables.) 【USB C Adapter with 3.3ft Long Cord】USB 3.0 to Ethernet Adapter with 3.3ft Long Cord sets up your workstation whatever you want. Adjust the location for maximum comfort and productivity. Built in 3.3ft (100cm) extension long cable can extend hard-to-reach USB ports to your desired location, which makes it ideal for desktop computers. 【Network Indicator 】USB Ethernet Adapter is designed network detection indicator. You can clearly see the working status of the network card by diagnostic indicator (Green light: Network power ; Yellow light: Network Data Transfer；Red Light： Connecting equipment)',
  'image': 'https://m.media-amazon.com/images/I/41WsGRr-3TL._AC_.jpg',
  'rating_number': 148,
  'price': 14.99,
  'average_rating': 4.2,
  'parent_asin': 'B0BKPB2YQ9'},
 {'preprocessed_description': 'HDMI Switch 3 in 1 Out 4K UHD HDMI Switcher Splitter, Automatic Switch with Remote Metal HDMI Switch Box Hub Support 4K 30Hz 3D 1080P HDCP1.4 for PS5 PS4 Xbox DVD Player Fire Stick Apple TV PC 📍3-Port HDMI Switch: This aluminum HDMI switch 3 in 1 out supports connecting 3 HDMI devices (gaming consoles, TV box, DVD player etc.) to 1 HDMI display and toggle between them. Release you from plugging and unplugging HDMI cables. No lag, No drop in quality. 📍Convenient Remote Control: Come with an IR remote control; enable to swap video sources without leaving a comfortable couch. And it can automatically switch to the device turned on, hassle-free. LED indicates which port is active. Plug and play set up, no driver needed. 📍Support 4K Resolution: Durable HDMI Switch supports 4K, 3840x2160p@30Hz, 3D display, Full-HD 1080P, the picture quality remains crisp and clear. Support HDCP 1.4, LPCM, DOLBY AC3,DTS7.1, deep color 24bit, 30bit, 26bit. 📍Wide Compatibility: This HDMI switch is compatible with most HDMI source devices. Including Blu-ray players, DVD players, Xbox 360, PS3, PS4, PS5, Nintendo Switch, Receivers, Apple TV, Fire TV stick, Roku Stick, PC, Laptop, HDTV, HD Monitor, Projector. 📍Fast & Stable Transmission: This compact HDMI switcher with gold plated connector provides high bandwidth 3.4Gbps data transmission, Input and output AWG26 HDMI standard cable length could reach up to 5m. Powered by USB (USB cable included), ensures stable video transmission and better performance.',
  'image': 'https://m.media-amazon.com/images/I/41fsjaknf1L._AC_.jpg',
  'rating_number': 3331,
  'price': 18.98,
  'average_rating': 4.2,
  'parent_asin': 'B09MM5QT3R'},
 {'preprocessed_description': 'Smart Watch,Ip67 Waterproof Bluetooth Smartwatch for Android Phones,Sport Fitness Watch with Blood Pressure Oxygen Heart Rate Monitor Activity Tracker Compatiable for Android iOS Women Men Pink ',
  'image': 'https://m.media-amazon.com/images/I/51YFypeuZhL._AC_.jpg',
  'rating_number': 125,
  'price': nan,
  'average_rating': 3.4,
  'parent_asin': 'B09Q5TNDHY'},
 {'preprocessed_description': '(3 Pack) Cute Airpod Case for Airpods 2&1,3D Drink Kawaii Silicone Cartoon Food Funny Protective Cover Accessories Skin for Airpod 1&2 Gen Charging Case for Girls Boys-(Arizona+Sport Water+Takis) 【Compatible Airpods 1/2 】This case designed for airpods1/2 case, compatible with Apple Airpods 1 Gen & 2 Gen charging case.for design to accessorize your airpods 1/2 to be unique.(Not Include Airpods1/2 earphone and Airpods charging box). 【All round Protection】our case is easy to install and take off & not easy to fall, All round protection against bumps shockproof and dustproof ,they are able to absorb pressure when dropped and protects against scratches. easy portabl and secure against loss. 【High-Quality Materials】This case PVC premium safe silicone materials offers better elasticity and touch feeling, leaves no fingerprints and dirty. comfortable to hold, keep your Airpods 1/2 case more security. 【Perfect Gift】This 3 Pack AirPods 1/2 protective case with cute 3D super Sports style cartoon design is a perfect gift for any occasion for girls and boys, a great gift for birthday Good Christmas New Years or any occasion gift for the friends girls, kids boys,family and teenagers. 【Accessories Include】:1* Sprot Water Silicone Bottle AirPods Case,1* Purple Potato Chips Silicone Airpod Case, 1*Arizona Silicone Cute Airpod Case for AirPods 1/2 and 3*Keychain (if you have any questions with our product , please contact us,We will take care of all quality-related issues.(inclund full refund or new replace product))',
  'image': 'https://m.media-amazon.com/images/I/41V7Wi2ckbL._AC_.jpg',
  'rating_number': 335,
  'price': 11.99,
  'average_rating': 4.7,
  'parent_asin': 'B0BZJKX7MS'},
 {'preprocessed_description': 'Acer ED270R Sbiipx 27" 1500R Curved Zero-Frame Full HD (1920 x 1080) Gaming Monitor with AMD FreeSync Technology | 165Hz | 5ms (G to G) | Display Port & 2 x HDMI 1.4 Ports 27" Full HD (1920 x 1080) 1500R Curved Widescreen VA Display AMD FreeSync Technology | Brightness: 250 nits Response Time: 5ms (G to G) | Refresh Rate: 165Hz - Using Display Port or 144Hz - Using HDMI Port ZeroFrame Design Ports: 1 x Display Port, 2 x HDMI 1.4 Ports & 1 x Audio-out (HDMI and Display Port Cable Included)',
  'image': 'https://m.media-amazon.com/images/I/41c6e+4RUUL._AC_.jpg',
  'rating_number': 1482,
  'price': nan,
  'average_rating': 4.4,
  'parent_asin': 'B0BDWN4RHW'},
 {'preprocessed_description': 'oioaahkeo Window Mount for Wyze Cam V3, Adhesive Mount for Mounting Wyze Cam V3 on Window Glass(Black, 2 Pack) This mount is specially designed for mounting Wyze Cam V3 on the window glass Simply mount Wyze Cam V3(not included) on the window to get a better perspective without drilling To mount wyze cam v3 directly on the window and no glare will be caused(Need to turn off the night vision mode of camara) For mounting wyze cam v3 surveillance camera indoors to avoid it from being stolen and no need for long wiring It is very easy to mount it on the window and it does even better job than wall mount. Simply buy it without risk',
  'image': 'https://m.media-amazon.com/images/I/213QyZBADwL._AC_.jpg',
  'rating_number': 100,
  'price': 13.99,
  'average_rating': 4.5,
  'parent_asin': 'B09QGN5YT6'},
 {'preprocessed_description': "2Pack Lightning to 3.5 mm Headphone Jack Adapter, [MFi Certified] 2 in 1 Lightning to 3.5mm AUX Audio + Charger Splitter Compatible with iPhone 13/12/11/XS/XR/X 8/ Support Music Control,Can't for Call ",
  'image': 'https://m.media-amazon.com/images/I/31Z1yGUeZVL._AC_.jpg',
  'rating_number': 108,
  'price': nan,
  'average_rating': 3.7,
  'parent_asin': 'B0B4NJ8NKN'},
 {'preprocessed_description': "yobola Wireless Earbuds, Bluetooth Earbuds in Ear Deep Bass HiFi Stereo, IPX7 Waterproof Bluetooth Headphones 5.3 Touch Control, Wireless Headphones 4 Microphone Clear Call, Lightweight and Fit Bluetooth 5.3 - Wireless earbuds with advanced Bluetooth 5.3 technology, which can provide stable connection, don't worry about interruption on calling or listening to music; The wireless earbuds can last for over 5 hours playtime on a single charge. the charging case can last up to 25 hours. Clear Calls - Wireless earbuds with 4 microphone design and ENC noise cancellation technology, can suppress 90% of the noise, Clear and loud calls can be made in noisy environments; IPX7 sweat and water-resistant, Whether running, gym, outdoor sports or exercise, our wireless earbuds can make you feel great. the earbuds won’t fall out while you are running or jogging. HiFi Stereo - Our wireless headphones use the latest Bluetooth 5.3 technology and the most advanced components. Our design offer incredible sound quality with deep bass and crystal clear treble. Comfortable Design - Half in-ear design will let the wireless earbuds fit your ear firmly, the lightweight material provide safe wearing without pain and the ears won’t feel discomfort after you wearing for a long time. Perfect for your workout, sports,working, driving without easily falling out; Simply take the wireless earbuds out of the charging case and they will automatically connect to your phone (after being paired the first time). Touch Control - With high-tech touch technology, you can answer/hang up, play/pause, adjust volume, switch songs and activate siri with just a touch of the Bluetooth earbuds; Compatible with most Bluetooth music players, including iPhone, Samsung, Huawei, Android smartphones, PC and Mac.",
  'image': 'https://m.media-amazon.com/images/I/310RF+dAi7L._AC_.jpg',
  'rating_number': 1391,
  'price': 25.99,
  'average_rating': 4.6,
  'parent_asin': 'B0C747Q3K1'},
 {'preprocessed_description': 'Dash Cam Front and Rear Inside 3 Channel, Free 64GB SD Card, 1080P Dash Camera for Car with 4 IR Lamps, Three Way Car Cam Super Night Vision, 2.5 Inch LCD, Parking Mode G-Sensor, USB C, Loop Record 【Triple Camera Dash Cam for Comprehensive Coverage】This dash cam features three cameras that record simultaneously, with a 170 Degree wide angle front/interior camera view and a 150 Degree rear camera view to capture every detail and important evidence. 【Full HD 1080P Resolution and One-Key Switching】The advanced triple camera system captures 1080p video from the front camera, enhanced HD 720p video from the interior camera, and rear camera, all in smooth and clear quality. With one-key switching, you can easily switch between the front, inside, and rear cameras to view different angles of the vehicle. 【Superb Night Vision with 4 IR Lamps】Featuring a Sony image sensor and 4 IR night vision lamps with a large f/1.8 aperture, this car camera provides clear recordings even in low light conditions. The rear-facing camera accurately captures the driver and passengers even in complete darkness, making it ideal for rideshare drivers such as Uber, Lyft, and taxi. 【24/7 Parking Monitoring】The parking monitor function automatically powers on the dash cam and records emergency footage in the event of an impact or collision after the engine is turned off. Connect the dash cam to the fuse using the hardwire kit (sold separately, ASIN: B08RS3Z8M6) to keep it recording even when the engine is off. 【Loop Recording and Accident Emergency Lock】Loop recording overwrites the oldest videos when the SD card is full, ensuring continuous recording. The built-in G-sensor locks the emergency footage in the event of an accident, protecting it from overwriting and serving as valuable evidence. 【Worry-Free Customer Service】We offer a 45-day money-back guarantee and 12-month worry-free warranty. If you encounter any issues with this dash cam, feel free to reach out to us through Amazon or by emailing our support team, who will respond within 24 hours.',
  'image': 'https://m.media-amazon.com/images/I/51HTABET1lL._AC_.jpg',
  'rating_number': 376,
  'price': 79.98,
  'average_rating': 4.2,
  'parent_asin': 'B0BLTPRG3X'},
 {'preprocessed_description': "SOOPII 100W Right Angle USB C to USB C Cable,2Pack 4FT Zinc Alloy Braided Type-C Cable with LED Display for lphone 15, lPad Air/Pro,MacBook Pro,Samsung S23/S22/S10,Pixel,LG(1.2m,Black) 【User-friendly Right Angle Cable】With considerate 90 degrees right angle design, easy to play games, watch videos and read e-Books while charging comfortably. 【Smart LED Display】Real-time charging power visible, show charging status and signify high power process. Built-in smart chips monitoring the charging power and adjusting current and voltage automatically, avoiding damage to the battery in case of unstable current.(Please note display module just show charging power, it neither increase nor decrease charging current.) \uf0b7【100W High-Speed Charging】Supports up to 100W(20V 5A) charging speed,with a max output of 100W charger, SooPii USB C to USB C cable can charge any Type-C devices from phones to laptops. Pair with a 100W USB-C Power Delivery charger to power up a MacBook Pro 16ʺ in 2 hours. (NOTE: This is a data transfer and USB 2.0 version charging cable, and does not support video output.) 【Ultimate Durability】 Based on 36,000+ bends strict tests, with special zinc alloy design and wearing rugged\xa0nylon braided exterior, SooPii Type-C Charging cable designed for longer service life and will never rupture. 【Widely Compatibility】Works effortlessly with any USB-C device including phones, tablets, and laptops. Compatible with lphone 15/ Pro Max/15 Pro/15 Plus/MacBook Pro 13'', MacBook Pro 15'', MacBook Air 2018, iPad Air 2020 10.9” (4th generation), iPad Pro 12.9''/11'', Samsung Galaxy S21/ S21 Ultra/ S20/ S20+/ S20 Ultra/ Note 10/ Note 10 Plus/ , Google Pixel 2/3/3a/4 XL, Switch/Switch Lite and more. (Note: Please use a 100W USB-C wall charger to achieve fast charging. ) 【What you Get in Box】1 x SooPii S40CC PD Fast Charging Cable and SooPii Worry-free 24-month Warranty and Our Lifetime Meticulous Service for any Problems,Concerns, Troubleshoots.",
  'image': 'https://m.media-amazon.com/images/I/41IXpDqFzLL.jpg',
  'rating_number': 667,
  'price': 15.29,
  'average_rating': 4.3,
  'parent_asin': 'B0CDRNNRCK'},
 {'preprocessed_description': "64GB Digital Voice Recorder - Voice Activated Recorder with Playback, Audio Recording Device for Lectures Meetings, USB Dictaphone Sound Tape Recorder MP3 ✔[Professional Voice Recorder]:[2022 Newest Version] Adopts the latest PCM ten-core triple digital intelligent noise reduction technology and 2 exclusive omnidirectional stereo microphones, this digital voice recorder can provide you with 1536kbps high-quality sound as if the speaker speaking standing by your side, you will enjoy clear recordings and playback easily ✔[Voice Activated Recorder]: Built-in automatic voice detecting function, auto-records and saves, no silent snippets or whisper in your recording, save space and time. Smart battery detection, it will automatically save the current recording when battery runs out, you don't need to worry about losing your files ✔[64GB Audio recorder]: This audio recording device has 64GB capacity which can save 800hrs of recording files or 30000 songs. Compatible with WIN/MAC, easily transfer files to computer via the supplied USB cable (MAC users need to download the VCL audio player to play the recording files). Easy file management, recording files can be saved with time stamp ✔[Simple & Multifunctional]: Easy to use. Just one-button to record, save and playback, make you never miss any important content with it! Not only a small voice recorder, it supports writing and can be used as an U disk. The design of the clip is convenient for you to wear on your coat or book. It's a prefect gift for students, professor, teacher, businessman, writer and blogger, anyone who loves to record ✔[What's In The Box] : Buy it now to get: 1x 64GB digital voice recorder+ USB cable+ 4x refills+ 1x earphone +user manual. AKALULI support 24-month free warranty to ensure your 100% satisfied purchasing experience",
  'image': 'https://m.media-amazon.com/images/I/51UuzxmVgIL._AC_.jpg',
  'rating_number': 2274,
  'price': 43.99,
  'average_rating': 3.8,
  'parent_asin': 'B09Q317Y3B'},

In [21]:
len(data_to_embed)

1000

In [22]:
text_to_embed = [item["preprocessed_description"] for item in data_to_embed]

In [23]:
text_to_embed

['Bosttor Bluetooth Beanie Hat with Light, Headlamp Cap with Headphones and Built-in Speaker Mic, Gifts for Men Women Teen 100% Acrylic Elastic closure Hand Wash Only 【Upgraded Bluetooth Beanie】Bosttor upgraded Bluetooth wireless technology offer much stable and strong connection, support music and calling, easy and fast to pair with your devices. Maximum transmission distance up to 33 feet. Built-in Stereo Speakers & Mic, enhance your music listening experience. 【Long Working Time Music Hat】Built with easy-access USB charging port, simply charge it via the included USD cable. It takes 1-2 hours to get full charged. The battery offers continuous working hours up to 10 hours. Perfect for camping, hiking, skiing, hunting, jogging, cycling, dog walking, auto repair, etc. 【LED Headlight Light Up Your Way】Hands-free LED light is rechargeable and removable. You can remove it to charge by laptop, power bank, socket, car charger, etc. The 4 LED lights can light up to 30 feet away. It points directional light toward what your eyes are looking at. It has 3 brightness settings. 【One Size Fits Most】Bosttor unisex beanie hat is made from the ultra-soft acrylic blend material that provides excellent insulation against cold winter air. Elastic and comfortable LED hat fits men women and teens. It is hand washable, please remove the LED and the headset before washing. 【Ideal Birthday & Christmas Gifts】Our beanie hat with Bluetooth and LED headlight is the ideal gift for runners and outdoor adventurers in winter. It is also your best gift choice for men women and teenagers. This is the perfect gift for anyone in the family and your friends. Your Ideal choice for Thanksgiving Day, Christmas, Birthday and Anniversary.',
 'Aceele USB and USB C to Ethernet Adapter, 3.3ft Long Cord,Aluminum 3 Ports USB 3.0 Hub with RJ45 10/100/1000 Gigabit Ethernet Adapter, RJ45+Gigabit LAN Network Adapter with USB C Adapter for Laptop 【USB or USB C to Ethernet Adapter】The Ethernet adapter comes with a USB C adapter which to connect to Ethernet whether the computer only USB C interface or USB A interface, also easily transform the type-C port on the device to 3 Type A ports, , allows you use network and other USB devices at the same time. 【Extra 3 USB 3.0 Ports】This Ethernet adapter offers extra 3ports USB 3.0 ports,USB port data transfer feed up to 5 Gbps speed, 10x faster than USB 2.0(480 Mbps). Faster transfer HD movie in seconds at blazing. ⛔Note: To ensure the best performance of this USB 3.0 hub, please do not use it for charging purposes, data transfer only. 【RJ45 Gigabit Ethernet Adapter】The usb c to ethernet adapter provides access to superfast network speed, up to 1000Mbps, backward compatible with 10Mbps / 100Mbps. It can provide a more stable connection than WiFi. Our ethernet adapter for laptop supports large downloads at maximum speeds without interruption. Is a perfect solution to buffer-free movie streaming, online gaming, data transferring, and video conferencing. (⛔To reach 1Gbps, make sure to use CAT6 & up Ethernet cables.) 【USB C Adapter with 3.3ft Long Cord】USB 3.0 to Ethernet Adapter with 3.3ft Long Cord sets up your workstation whatever you want. Adjust the location for maximum comfort and productivity. Built in 3.3ft (100cm) extension long cable can extend hard-to-reach USB ports to your desired location, which makes it ideal for desktop computers. 【Network Indicator 】USB Ethernet Adapter is designed network detection indicator. You can clearly see the working status of the network card by diagnostic indicator (Green light: Network power ; Yellow light: Network Data Transfer；Red Light： Connecting equipment)',
 'HDMI Switch 3 in 1 Out 4K UHD HDMI Switcher Splitter, Automatic Switch with Remote Metal HDMI Switch Box Hub Support 4K 30Hz 3D 1080P HDCP1.4 for PS5 PS4 Xbox DVD Player Fire Stick Apple TV PC 📍3-Port HDMI Switch: This aluminum HDMI switch 3 in 1 out supports connecting 3 HDMI devices (gaming consoles, TV box, DVD player etc.) to 1 HDMI display and toggle between them. Release you from plugging and unplugging HDMI cables. No lag, No drop in quality. 📍Convenient Remote Control: Come with an IR remote control; enable to swap video sources without leaving a comfortable couch. And it can automatically switch to the device turned on, hassle-free. LED indicates which port is active. Plug and play set up, no driver needed. 📍Support 4K Resolution: Durable HDMI Switch supports 4K, 3840x2160p@30Hz, 3D display, Full-HD 1080P, the picture quality remains crisp and clear. Support HDCP 1.4, LPCM, DOLBY AC3,DTS7.1, deep color 24bit, 30bit, 26bit. 📍Wide Compatibility: This HDMI switch is compatible with most HDMI source devices. Including Blu-ray players, DVD players, Xbox 360, PS3, PS4, PS5, Nintendo Switch, Receivers, Apple TV, Fire TV stick, Roku Stick, PC, Laptop, HDTV, HD Monitor, Projector. 📍Fast & Stable Transmission: This compact HDMI switcher with gold plated connector provides high bandwidth 3.4Gbps data transmission, Input and output AWG26 HDMI standard cable length could reach up to 5m. Powered by USB (USB cable included), ensures stable video transmission and better performance.',
 'Smart Watch,Ip67 Waterproof Bluetooth Smartwatch for Android Phones,Sport Fitness Watch with Blood Pressure Oxygen Heart Rate Monitor Activity Tracker Compatiable for Android iOS Women Men Pink ',
 '(3 Pack) Cute Airpod Case for Airpods 2&1,3D Drink Kawaii Silicone Cartoon Food Funny Protective Cover Accessories Skin for Airpod 1&2 Gen Charging Case for Girls Boys-(Arizona+Sport Water+Takis) 【Compatible Airpods 1/2 】This case designed for airpods1/2 case, compatible with Apple Airpods 1 Gen & 2 Gen charging case.for design to accessorize your airpods 1/2 to be unique.(Not Include Airpods1/2 earphone and Airpods charging box). 【All round Protection】our case is easy to install and take off & not easy to fall, All round protection against bumps shockproof and dustproof ,they are able to absorb pressure when dropped and protects against scratches. easy portabl and secure against loss. 【High-Quality Materials】This case PVC premium safe silicone materials offers better elasticity and touch feeling, leaves no fingerprints and dirty. comfortable to hold, keep your Airpods 1/2 case more security. 【Perfect Gift】This 3 Pack AirPods 1/2 protective case with cute 3D super Sports style cartoon design is a perfect gift for any occasion for girls and boys, a great gift for birthday Good Christmas New Years or any occasion gift for the friends girls, kids boys,family and teenagers. 【Accessories Include】:1* Sprot Water Silicone Bottle AirPods Case,1* Purple Potato Chips Silicone Airpod Case, 1*Arizona Silicone Cute Airpod Case for AirPods 1/2 and 3*Keychain (if you have any questions with our product , please contact us,We will take care of all quality-related issues.(inclund full refund or new replace product))',
 'Acer ED270R Sbiipx 27" 1500R Curved Zero-Frame Full HD (1920 x 1080) Gaming Monitor with AMD FreeSync Technology | 165Hz | 5ms (G to G) | Display Port & 2 x HDMI 1.4 Ports 27" Full HD (1920 x 1080) 1500R Curved Widescreen VA Display AMD FreeSync Technology | Brightness: 250 nits Response Time: 5ms (G to G) | Refresh Rate: 165Hz - Using Display Port or 144Hz - Using HDMI Port ZeroFrame Design Ports: 1 x Display Port, 2 x HDMI 1.4 Ports & 1 x Audio-out (HDMI and Display Port Cable Included)',
 'oioaahkeo Window Mount for Wyze Cam V3, Adhesive Mount for Mounting Wyze Cam V3 on Window Glass(Black, 2 Pack) This mount is specially designed for mounting Wyze Cam V3 on the window glass Simply mount Wyze Cam V3(not included) on the window to get a better perspective without drilling To mount wyze cam v3 directly on the window and no glare will be caused(Need to turn off the night vision mode of camara) For mounting wyze cam v3 surveillance camera indoors to avoid it from being stolen and no need for long wiring It is very easy to mount it on the window and it does even better job than wall mount. Simply buy it without risk',
 "2Pack Lightning to 3.5 mm Headphone Jack Adapter, [MFi Certified] 2 in 1 Lightning to 3.5mm AUX Audio + Charger Splitter Compatible with iPhone 13/12/11/XS/XR/X 8/ Support Music Control,Can't for Call ",
 "yobola Wireless Earbuds, Bluetooth Earbuds in Ear Deep Bass HiFi Stereo, IPX7 Waterproof Bluetooth Headphones 5.3 Touch Control, Wireless Headphones 4 Microphone Clear Call, Lightweight and Fit Bluetooth 5.3 - Wireless earbuds with advanced Bluetooth 5.3 technology, which can provide stable connection, don't worry about interruption on calling or listening to music; The wireless earbuds can last for over 5 hours playtime on a single charge. the charging case can last up to 25 hours. Clear Calls - Wireless earbuds with 4 microphone design and ENC noise cancellation technology, can suppress 90% of the noise, Clear and loud calls can be made in noisy environments; IPX7 sweat and water-resistant, Whether running, gym, outdoor sports or exercise, our wireless earbuds can make you feel great. the earbuds won’t fall out while you are running or jogging. HiFi Stereo - Our wireless headphones use the latest Bluetooth 5.3 technology and the most advanced components. Our design offer incredible sound quality with deep bass and crystal clear treble. Comfortable Design - Half in-ear design will let the wireless earbuds fit your ear firmly, the lightweight material provide safe wearing without pain and the ears won’t feel discomfort after you wearing for a long time. Perfect for your workout, sports,working, driving without easily falling out; Simply take the wireless earbuds out of the charging case and they will automatically connect to your phone (after being paired the first time). Touch Control - With high-tech touch technology, you can answer/hang up, play/pause, adjust volume, switch songs and activate siri with just a touch of the Bluetooth earbuds; Compatible with most Bluetooth music players, including iPhone, Samsung, Huawei, Android smartphones, PC and Mac.",
 'Dash Cam Front and Rear Inside 3 Channel, Free 64GB SD Card, 1080P Dash Camera for Car with 4 IR Lamps, Three Way Car Cam Super Night Vision, 2.5 Inch LCD, Parking Mode G-Sensor, USB C, Loop Record 【Triple Camera Dash Cam for Comprehensive Coverage】This dash cam features three cameras that record simultaneously, with a 170 Degree wide angle front/interior camera view and a 150 Degree rear camera view to capture every detail and important evidence. 【Full HD 1080P Resolution and One-Key Switching】The advanced triple camera system captures 1080p video from the front camera, enhanced HD 720p video from the interior camera, and rear camera, all in smooth and clear quality. With one-key switching, you can easily switch between the front, inside, and rear cameras to view different angles of the vehicle. 【Superb Night Vision with 4 IR Lamps】Featuring a Sony image sensor and 4 IR night vision lamps with a large f/1.8 aperture, this car camera provides clear recordings even in low light conditions. The rear-facing camera accurately captures the driver and passengers even in complete darkness, making it ideal for rideshare drivers such as Uber, Lyft, and taxi. 【24/7 Parking Monitoring】The parking monitor function automatically powers on the dash cam and records emergency footage in the event of an impact or collision after the engine is turned off. Connect the dash cam to the fuse using the hardwire kit (sold separately, ASIN: B08RS3Z8M6) to keep it recording even when the engine is off. 【Loop Recording and Accident Emergency Lock】Loop recording overwrites the oldest videos when the SD card is full, ensuring continuous recording. The built-in G-sensor locks the emergency footage in the event of an accident, protecting it from overwriting and serving as valuable evidence. 【Worry-Free Customer Service】We offer a 45-day money-back guarantee and 12-month worry-free warranty. If you encounter any issues with this dash cam, feel free to reach out to us through Amazon or by emailing our support team, who will respond within 24 hours.',
 "SOOPII 100W Right Angle USB C to USB C Cable,2Pack 4FT Zinc Alloy Braided Type-C Cable with LED Display for lphone 15, lPad Air/Pro,MacBook Pro,Samsung S23/S22/S10,Pixel,LG(1.2m,Black) 【User-friendly Right Angle Cable】With considerate 90 degrees right angle design, easy to play games, watch videos and read e-Books while charging comfortably. 【Smart LED Display】Real-time charging power visible, show charging status and signify high power process. Built-in smart chips monitoring the charging power and adjusting current and voltage automatically, avoiding damage to the battery in case of unstable current.(Please note display module just show charging power, it neither increase nor decrease charging current.) \uf0b7【100W High-Speed Charging】Supports up to 100W(20V 5A) charging speed,with a max output of 100W charger, SooPii USB C to USB C cable can charge any Type-C devices from phones to laptops. Pair with a 100W USB-C Power Delivery charger to power up a MacBook Pro 16ʺ in 2 hours. (NOTE: This is a data transfer and USB 2.0 version charging cable, and does not support video output.) 【Ultimate Durability】 Based on 36,000+ bends strict tests, with special zinc alloy design and wearing rugged\xa0nylon braided exterior, SooPii Type-C Charging cable designed for longer service life and will never rupture. 【Widely Compatibility】Works effortlessly with any USB-C device including phones, tablets, and laptops. Compatible with lphone 15/ Pro Max/15 Pro/15 Plus/MacBook Pro 13'', MacBook Pro 15'', MacBook Air 2018, iPad Air 2020 10.9” (4th generation), iPad Pro 12.9''/11'', Samsung Galaxy S21/ S21 Ultra/ S20/ S20+/ S20 Ultra/ Note 10/ Note 10 Plus/ , Google Pixel 2/3/3a/4 XL, Switch/Switch Lite and more. (Note: Please use a 100W USB-C wall charger to achieve fast charging. ) 【What you Get in Box】1 x SooPii S40CC PD Fast Charging Cable and SooPii Worry-free 24-month Warranty and Our Lifetime Meticulous Service for any Problems,Concerns, Troubleshoots.",
 "64GB Digital Voice Recorder - Voice Activated Recorder with Playback, Audio Recording Device for Lectures Meetings, USB Dictaphone Sound Tape Recorder MP3 ✔[Professional Voice Recorder]:[2022 Newest Version] Adopts the latest PCM ten-core triple digital intelligent noise reduction technology and 2 exclusive omnidirectional stereo microphones, this digital voice recorder can provide you with 1536kbps high-quality sound as if the speaker speaking standing by your side, you will enjoy clear recordings and playback easily ✔[Voice Activated Recorder]: Built-in automatic voice detecting function, auto-records and saves, no silent snippets or whisper in your recording, save space and time. Smart battery detection, it will automatically save the current recording when battery runs out, you don't need to worry about losing your files ✔[64GB Audio recorder]: This audio recording device has 64GB capacity which can save 800hrs of recording files or 30000 songs. Compatible with WIN/MAC, easily transfer files to computer via the supplied USB cable (MAC users need to download the VCL audio player to play the recording files). Easy file management, recording files can be saved with time stamp ✔[Simple & Multifunctional]: Easy to use. Just one-button to record, save and playback, make you never miss any important content with it! Not only a small voice recorder, it supports writing and can be used as an U disk. The design of the clip is convenient for you to wear on your coat or book. It's a prefect gift for students, professor, teacher, businessman, writer and blogger, anyone who loves to record ✔[What's In The Box] : Buy it now to get: 1x 64GB digital voice recorder+ USB cable+ 4x refills+ 1x earphone +user manual. AKALULI support 24-month free warranty to ensure your 100% satisfied purchasing experience",
 "Raycon Work Earbuds Classic Bluetooth 5.2 Wireless with Noise Cancellation, Awareness Mode, 33 Hours of Battery, IPX5 Waterproof (Carbon Black) 💼 THE TRUE WIRELESS EXPERIENCE | Stay focused on your work and in tune with your coworkers. Seamless collaboration and communication without compromise. With 33 hours of battery life on The Work Earbuds Classic, you can get the job done, even if it takes all day! 💼 PERSONALIZED EXPERIENCE | With a customizable set of gel tips, you can get a perfect fit! Each package comes with a set of four differently sized gel tips! The perfect fit improves Active Noise Cancellation mode so you’re guaranteed to stay focused. Need to listen into work conversations or stay aware while you’re commuting? Awareness mode has your back! The memory foam gel tips form to your ears for the ultimate comfortable and blissful listening experience. 💼 VIVID VOICE MICROPHONE | Clean, crisp, sound that speaks for itself. Say goodbye to having to repeat yourself over video call multiple times. Your colleagues will hear you loud and crystal clear. Group collaborations become seamless when communication is fluid. Designed for a work experience like no other. 💼 ALL-DAY BATTERY WITH WIRELESS CHARGING | The work earbuds classic are built for your best work day. All day battery with a portable wireless charging case that will brighten your work week up. Play your favorite podcasts and tunes that will liven every step. Set it and forget it - Once the day is done, pop your earbuds into the charging capsule and onto a wireless charging pad. It’s as easy as 1,2,3! (*Wireless charging pad not included*) The Raycon Limited Warranty only covers manufacturer’s defects for up to the first year the device's purchase date. These include: Volume imbalance, Pairing issues, Charging issues Broken piece (not caused by normal wear), Single-play issues.The warranty excludes defects or damage to the product resulting from; normal wear and tear, neglect, misuse, accident, improper application, or any other customer-induced damage; unauthorized repair or modification by customer or third party; shipping damage occurring while the product is in transit; or any other conditions whatsoever that are beyond the control of the company",
 'iPad 10.9 Case for iPad Air Case 5th/4th Generation, Cutebricase iPad Air 5/4 Case Multi-Angle Viewing Case with Adjustable Stand Soft PU Leather Back Cover with Auto Wake/Sleep,Tree of Life [Applicable Models]: Only compatible with iPad Air 5th Generation Case 2022 (Model Number: A2588/A2589/A2591) and iPad Air 4th Generation Case 10.9 inch 2020(Model Number: A2072/A2316/A2324/A2325). Not compatible with any other devices. [Stable & Sturdy & Adjustable]: All-around protection for your Apple iPad. With the anti-slip microfiber lining material, you are allowed to set up the iPad 10.9 case multiple horizontal stand angles for viewing or typing, no more angle limitation. [Reliable Material]: Made of sturdy PC frame with Epoxy Resin Board interlayer, and durable PU leather exterior, the iPad 10.9 inch Air 5/4 Generation case provides total front-and-back protection against fingerprints and scratches. Waterproof, stain-resistant and easy to clean. [No deformation in a long term] [Never-Fade]. Air cushion technology and honeycomb assure more effective shock absorb and thermal dissipation. [Smart Auto Sleep/Wake Function & Support Touch ID & Support Apple Pencil 2nd Gen Attached Charging Mode]: This magnetic iPad 10.9 inch air 5th/4th gen iPad Cover instantly wakes up iPad when opened, and makes it go to sleep once closed (extend battery life). Top Button opening design easy for you to identify fingerprints, fast and convenience user experience. [Insist on Original Design]:Cutebricase is a team that focuses on original design. This protective iPad 10.9 inch Air 5th/4th Gen iPad cover with bright colors flowers and bees design makes your iPad look pretty and unique. Ideal gift for men, women kids, boys and girls.',

In [24]:
embeddings = get_embeddings_batch(text_to_embed)

Processed 100 of 1000
Processed 200 of 1000
Processed 300 of 1000
Processed 400 of 1000
Processed 500 of 1000
Processed 600 of 1000
Processed 700 of 1000
Processed 800 of 1000
Processed 900 of 1000
Processed 1000 of 1000

In [25]:
len(embeddings)

1000

In [26]:
pointstructs = []
i=1
for embedding, data in zip(embeddings, data_to_embed):
    pointstructs.append(
        PointStruct(
            id=i,
            vector={
                "text-embedding-3-small": embedding,
                "bm25": Document(
                    text=data["preprocessed_description"],
                    model="qdrant/bm25"
                )
            },
            payload=data
        )
    )
    i += 1

In [ ]:
pointstructs[0].vector

PointStruct(id=1, vector={'text-embedding-3-small': [0.0118865966796875, 0.010284423828125, 0.001575469970703125, -0.0296478271484375, -0.071044921875, -0.08697509765625, -0.0194854736328125, 0.01470184326171875, 0.0391845703125, -0.07940673828125, -0.00606536865234375, 0.0215911865234375, -0.04974365234375, -0.005542755126953125, 0.01103973388671875, 0.0234832763671875, -0.0701904296875, -0.033050537109375, -0.042572021484375, 0.0285797119140625, -0.0287322998046875, 0.01416015625, 0.00426483154296875, -0.007625579833984375, 0.01715087890625, 0.046478271484375, -0.0203857421875, 0.0215911865234375, 0.05206298828125, 0.001247406005859375, -0.04241943359375, -0.0261077880859375, 0.026702880859375, -0.025299072265625, -0.0080413818359375, 0.0039043426513671875, 0.014251708984375, -0.061553955078125, 0.0335693359375, -0.01151275634765625, -0.0034351348876953125, -0.0303192138671875, 0.06793212890625, 0.001667022705078125, 0.0121307373046875, -0.012176513671875, -0.03009033203125, 0.0187530517578125, -0.021392822265625, 0.0433349609375, -0.0136260986328125, 0.031402587890625, -0.004482269287109375, 0.0472412109375, -0.034149169921875, -0.0291748046875, 0.0078887939453125, 0.0251617431640625, 0.035980224609375, 0.037933349609375, 0.0283203125, 0.0003638267517089844, -0.006191253662109375, 0.034942626953125, -0.008758544921875, -0.0203399658203125, -0.004077911376953125, -0.01020050048828125, -0.038299560546875, -0.0277557373046875, 0.034515380859375, 0.01123046875, -0.0090789794921875, -0.044952392578125, -0.038421630859375, 0.0233917236328125, 0.0122528076171875, -0.0428466796875, 0.048004150390625, 0.03668212890625, 0.0190582275390625, -0.0219879150390625, -0.0328369140625, 0.0033168792724609375, -0.035369873046875, -0.00913238525390625, -0.049468994140625, -0.048553466796875, -0.028533935546875, -0.04791259765625, -0.01390838623046875, -0.020843505859375, 0.0233917236328125, -0.0249176025390625, -0.0311126708984375, -0.00994873046875, -0.049713134765625, 0.001956939697265625, -0.0031185150146484375, -0.00066375732421875, 0.06402587890625, -0.02490234375, -0.007694244384765625, -0.04669189453125, -0.0088043212890625, 0.0159149169921875, -0.0202178955078125, -0.01390838623046875, -0.032928466796875, 0.055816650390625, -0.042572021484375, 0.0174102783203125, 0.0011243820190429688, 0.01514434814453125, -0.0133056640625, 0.00485992431640625, 0.0202484130859375, -0.032745361328125, 0.00951385498046875, 0.01436614990234375, 0.0008187294006347656, 0.0426025390625, 0.00592803955078125, -0.022796630859375, -0.01209259033203125, -0.014495849609375, 0.01210784912109375, -0.0128021240234375, -0.0105133056640625, -0.01224517822265625, -0.030426025390625, 0.016937255859375, 0.11529541015625, 2.7060508728027344e-05, -0.00960540771484375, -0.046142578125, -0.0161285400390625, -0.0038433074951171875, -0.002811431884765625, -0.0191192626953125, 0.01055145263671875, -0.05609130859375, -0.006526947021484375, -0.0057525634765625, 0.0266571044921875, 0.037506103515625, 0.060028076171875, -0.01227569580078125, -0.0246429443359375, 0.036041259765625, 0.0092010498046875, -0.033843994140625, -0.017303466796875, 0.02685546875, 0.0113525390625, 0.0030803680419921875, 0.0080413818359375, 0.07183837890625, -0.05206298828125, -0.0266265869140625, 0.0211029052734375, -0.0125579833984375, -0.01361083984375, -0.0142059326171875, 0.04022216796875, 0.04571533203125, 0.0030841827392578125, -0.0305023193359375, -0.0621337890625, -0.0296478271484375, 0.0322265625, -0.0517578125, -0.0205841064453125, -0.00986480712890625, -0.0049896240234375, -0.0047760009765625, 0.00408172607421875, 0.01033782958984375, 0.00018286705017089844, 0.00376129150390625, 0.02288818359375, -0.036773681640625, 0.042694091796875, -0.046966552734375, -0.0465087890625, 0.0100555419921875, -0.058074951171875, 0.02899169921875, -0.01515960693359375, -0.0123443603515625, -0.023284912109375, 0.00505828857421875, 0.0031795501708984375, 0.01409149169921875, -0.007709503173828125, -0.04388427734375, 0.0400390625, 0.040771484375, -0.0153961181640625, 0.01959228515625, -0.01116943359375, -0.0209503173828125, 0.01148223876953125, -0.003566741943359375, -0.0450439453125, -0.01123809814453125, -2.9206275939941406e-06, 0.049346923828125, 0.040069580078125, -0.040924072265625, 0.0487060546875, -0.0297698974609375, -0.01036834716796875, 0.026519775390625, -0.0107574462890625, 0.0274505615234375, 0.0250701904296875, -0.0232391357421875, -0.0521240234375, -0.01313018798828125, -0.0450439453125, 0.0236358642578125, -0.0006756782531738281, 0.020355224609375, 0.002155303955078125, -0.0244903564453125, -0.0018978118896484375, 0.006656646728515625, 0.033294677734375, -0.0196533203125, -0.01092529296875, -0.0211029052734375, -0.023712158203125, -0.0010576248168945312, -0.0168304443359375, -0.0197296142578125, -0.04144287109375, -0.0218048095703125, 0.01079559326171875, -0.059539794921875, -0.04150390625, -0.0189361572265625, 0.0148468017578125, 0.005859375, -0.0028553009033203125, 0.004970550537109375, -0.0384521484375, -0.046600341796875, 0.0113372802734375, 0.026885986328125, 0.02520751953125, 0.0109405517578125, -0.011474609375, 0.05303955078125, 0.0484619140625, -0.0090789794921875, 0.0190277099609375, 0.034332275390625, 0.00838470458984375, -0.04510498046875, -0.02752685546875, -0.02978515625, -0.03228759765625, 0.016815185546875, -0.0031280517578125, 0.005695343017578125, -0.011566162109375, 0.019744873046875, 0.0305938720703125, 0.00742340087890625, 0.01238250732421875, -0.0212249755859375, 0.002529144287109375, 0.048370361328125, 0.0160064697265625, -0.00887298583984375, 0.00440216064453125, 0.005504608154296875, -4.0650367736816406e-05, 0.0124969482421875, 0.006999969482421875, 0.045623779296875, 0.02203369140625, -0.038116455078125, -0.0160980224609375, 0.0301513671875, 0.0048675537109375, -0.007640838623046875, -0.0196075439453125, -0.0167083740234375, 0.026885986328125, 0.010467529296875, 0.02056884765625, 0.010040283203125, 0.0238037109375, 0.01102447509765625, 0.026885986328125, 0.004791259765625, -0.047637939453125, -0.0328369140625, 0.009307861328125, 0.028594970703125, 0.01374053955078125, 0.015960693359375, 0.01702880859375, 0.057708740234375, -0.042144775390625, -0.0201263427734375, 0.028717041015625, -0.014068603515625, -0.0151824951171875, 0.0065155029296875, -0.021331787109375, -0.00141143798828125, 0.00775146484375, -0.048828125, -0.0136566162109375, -0.05157470703125, 0.00717926025390625, -0.057098388671875, -0.0178985595703125, 0.01491546630859375, 0.00159454345703125, 0.0299530029296875, 0.0291900634765625, -0.019500732421875, -0.0163116455078125, -0.007720947265625, -0.0016298294067382812, -0.05029296875, 0.00991058349609375, 0.0219879150390625, -0.008392333984375, 0.002719879150390625, -0.0214385986328125, -0.0296783447265625, -0.019744873046875, 0.0010480880737304688, -0.0025539398193359375, 0.00933837890625, -0.01285552978515625, 0.00628662109375, -0.06201171875, 0.0309600830078125, 0.033660888671875, 0.0264434814453125, 0.005619049072265625, -0.033843994140625, -0.0511474609375, 0.030242919921875, -0.006237030029296875, -0.01422119140625, 0.0272064208984375, -0.03631591796875, 0.0013113021850585938, 0.003597259521484375, 0.06365966796875, -0.0096588134765625, -0.003131866455078125, -0.0038242340087890625, -0.01424407958984375, 0.04815673828125, -0.0010280609130859375, 0.0108642578125, -0.003875732421875, 0.0193023681640625, -0.062225341796875, -0.0015621185302734375, -0.0562744140625, -0.0178375244140625, 0.0019664764404296875, 0.0364990234375, 0.030242919921875, 0.028167724609375, -0.0222930908203125, 0.0031833648681640625, -0.00258636474609375, 0.026580810546875, -0.039581298828125, 0.0105743408203125, -0.0300445556640625, -0.00357818603515625, -0.00930023193359375, 0.007526397705078125, 0.01174163818359375, 0.036773681640625, 0.02789306640625, 0.0286407470703125, -0.00467681884765625, -0.05499267578125, 0.06317138671875, -0.0258331298828125, -0.02606201171875, -0.0010700225830078125, 0.0633544921875, 0.036041259765625, 0.037811279296875, 0.03070068359375, -0.0044097900390625, 0.018890380859375, 0.022705078125, -0.0310516357421875, -0.03790283203125, -0.0149383544921875, -0.0004744529724121094, 0.004878997802734375, -0.019744873046875, 0.0233154296875, -0.009307861328125, 0.017730712890625, -0.00498199462890625, -0.033935546875, -0.00021016597747802734, 0.006481170654296875, 0.06744384765625, 0.0228118896484375, -0.04302978515625, -0.031768798828125, 0.0284576416015625, -0.033111572265625, 0.00136566162109375, -0.059356689453125, -0.0056915283203125, -0.0120697021484375, -0.033111572265625, 0.004642486572265625, 0.03790283203125, -0.048065185546875, -0.028594970703125, -0.035888671875, -0.0313720703125, 0.0050048828125, 0.01532745361328125, -0.006793975830078125, -0.010467529296875, -0.0074920654296875, 0.0172882080078125, 0.07781982421875, -0.0027942657470703125, 0.00791168212890625, 0.044586181640625, 0.0106964111328125, -0.03533935546875, 0.009735107421875, 0.02490234375, -0.0195770263671875, -0.03131103515625, 0.07843017578125, -0.058746337890625, -0.0303802490234375, 0.017303466796875, -0.036773681640625, 0.0029888153076171875, 0.035400390625, -0.01152801513671875, 0.0205841064453125, 0.018310546875, -0.0161895751953125, -0.056365966796875, 0.00885772705078125, 0.007740020751953125, -0.06732177734375, 0.029693603515625, -0.03558349609375, -0.002422332763671875, 0.0259857177734375, 0.01146697998046875, -0.0008707046508789062, 0.04486083984375, -0.01236724853515625, 0.049285888671875, 0.05023193359375, -0.0133056640625, 0.0036773681640625, 0.068603515625, -0.01213836669921875, 0.034576416015625, -0.004619598388671875, -0.00131988525390625, -0.016082763671875, 0.010162353515625, 0.00412750244140625, -0.017791748046875, -0.00844573974609375, -0.0023479461669921875, -0.0333251953125, 0.047149658203125, 0.01224517822265625, -0.0562744140625, 0.00365447998046875, -0.0038661956787109375, -0.04669189453125, -0.007251739501953125, -0.00835418701171875, 0.038299560546875, -0.00864410400390625, -0.09521484375, -0.002986907958984375, -0.034027099609375, 0.0031375885009765625, 0.04901123046875, -0.005481719970703125, 0.0195159912109375, 0.0404052734375, 0.0119781494140625, 0.04412841796875, 0.05322265625, -0.01276397705078125, -0.04437255859375, -0.016571044921875, -0.04901123046875, -0.0020694732666015625, -1.9311904907226562e-05, 0.01058197021484375, -0.00762939453125, -0.024169921875, -0.023712158203125, 0.0255279541015625, -0.0178985595703125, 0.0050201416015625, -0.0284881591796875, 0.021575927734375, 0.032012939453125, 0.00687408447265625, 0.004344940185546875, -0.009033203125, -0.02734375, -0.037200927734375, -0.05133056640625, 0.007366180419921875, -0.005939483642578125, 0.00665283203125, -0.043792724609375, -0.0458984375, 0.0037555694580078125, 0.006313323974609375, -0.00412750244140625, -0.026397705078125, -0.026611328125, -0.007762908935546875, -0.004856109619140625, 0.0015897750854492188, -0.00736236572265625, 0.000164031982421875, 0.01218414306640625, -0.00038433074951171875, -0.0305938720703125, -0.00865936279296875, 0.0201263427734375, -0.03662109375, 0.01708984375, 0.0186614990234375, 0.0227813720703125, -0.01275634765625, -0.007389068603515625, -0.0185394287109375, -0.005401611328125, -0.040557861328125, 0.017913818359375, -0.0034427642822265625, 0.05377197265625, -0.02093505859375, -0.014129638671875, 0.0139923095703125, 0.01169586181640625, 0.02471923828125, 0.0015163421630859375, 0.060089111328125, -0.004058837890625, 0.0020580291748046875, -0.018646240234375, -0.0396728515625, -0.01255035400390625, -0.042083740234375, 0.058441162109375, 0.018218994140625, -0.002201080322265625, -0.03277587890625, -0.0307464599609375, 0.00965118408203125, -0.033843994140625, 0.0210723876953125, -0.0232086181640625, 0.0122222900390625, -0.0248260498046875, -0.022979736328125, 0.0035724639892578125, -0.036865234375, -0.015655517578125, 0.026336669921875, -0.0300445556640625, -0.00426483154296875, 0.0273590087890625, 0.0088043212890625, 0.004039764404296875, -0.0231475830078125, -0.029052734375, -0.0123138427734375, -0.0064239501953125, -0.0177001953125, 0.010009765625, -0.017242431640625, -0.005825042724609375, 0.01424407958984375, -0.01983642578125, 0.0026798248291015625, 0.0386962890625, -0.05010986328125, 0.00146484375, 0.0282135009765625, -0.0012912750244140625, 0.03302001953125, 0.033233642578125, -0.03411865234375, -0.044952392578125, -0.00017249584197998047, 0.013153076171875, -0.0046234130859375, 0.0198822021484375, 0.01050567626953125, -0.0291900634765625, -0.0098876953125, 0.0284881591796875, 0.0303192138671875, -0.0095062255859375, 0.01149749755859375, 0.0079193115234375, -0.04278564453125, 0.04827880859375, 0.01378631591796875, 0.01010894775390625, 0.021636962890625, 0.0205078125, -0.0113983154296875, -0.0280303955078125, -0.00955963134765625, -0.00975799560546875, 0.044952392578125, 0.0017576217651367188, -0.051239013671875, 0.027618408203125, -0.03289794921875, 0.00429534912109375, -0.022430419921875, 0.00046253204345703125, 0.01513671875, -0.057647705078125, -0.0161590576171875, -0.044769287109375, -0.00841522216796875, 0.00745391845703125, -0.0010509490966796875, 0.039581298828125, -0.0032176971435546875, 0.0083465576171875, 0.029083251953125, -0.004241943359375, 0.01580810546875, 0.05029296875, -0.033905029296875, -0.04156494140625, -0.00830841064453125, -0.0045623779296875, -0.03363037109375, 0.0051116943359375, 0.03216552734375, 0.0284881591796875, 0.029876708984375, 0.007602691650390625, -0.0015659332275390625, -0.005176544189453125, -0.0046539306640625, 0.011444091796875, -0.0121612548828125, 0.037353515625, 0.040496826171875, 0.027130126953125, -0.0172882080078125, 0.002201080322265625, 0.0121307373046875, 0.032073974609375, 0.0125274658203125, -0.054412841796875, -0.05096435546875, 0.01116943359375, 0.003963470458984375, 0.01268768310546875, 0.006256103515625, -0.0093536376953125, -0.0232391357421875, -0.002033233642578125, -0.01552581787109375, 0.00017070770263671875, 0.04217529296875, 0.04742431640625, 0.02325439453125, 0.006000518798828125, 0.0009322166442871094, -0.032135009765625, -0.0094451904296875, -0.035064697265625, -0.039215087890625, 0.00463104248046875, -0.051788330078125, -0.03704833984375, 0.02850341796875, 0.01084136962890625, 0.04241943359375, 0.009307861328125, 0.011993408203125, -0.034027099609375, -0.0184783935546875, -0.00502777099609375, 0.00904083251953125, 0.0312347412109375, -0.017425537109375, 0.03179931640625, 0.0245513916015625, 0.04888916015625, 0.006183624267578125, -0.00838470458984375, 0.017059326171875, 0.00995635986328125, -0.0019407272338867188, 0.048065185546875, 0.022247314453125, 0.0023059844970703125, -0.017974853515625, -0.05169677734375, 0.01922607421875, -0.005466461181640625, -0.01308441162109375, 0.01082611083984375, 0.027069091796875, -0.03680419921875, 0.0081787109375, -0.0095977783203125, -0.00083160400390625, -0.0122528076171875, -0.0477294921875, 0.0201263427734375, 0.005130767822265625, -0.03125, 0.004756927490234375, 0.0092926025390625, -0.019287109375, 0.0169219970703125, -0.0186614990234375, -0.029876708984375, -0.0201568603515625, -0.0306549072265625, 0.007537841796875, -0.00635528564453125, -0.01305389404296875, 0.00733184814453125, 0.0168304443359375, 0.010894775390625, 0.0125732421875, -0.0040435791015625, -0.021270751953125, -0.0406494140625, 0.002048492431640625, -0.01187896728515625, 0.003032684326171875, 0.0141754150390625, 0.0099334716796875, -0.04376220703125, -0.01209259033203125, -0.02642822265625, -0.0017156600952148438, 0.04351806640625, -0.041168212890625, 0.034942626953125, 0.0001850128173828125, -0.015045166015625, 0.02923583984375, -0.016082763671875, -0.0285491943359375, 0.005260467529296875, 0.004459381103515625, 0.0119781494140625, -0.00852203369140625, 0.00948333740234375, 0.021484375, -0.005222320556640625, -0.047332763671875, -0.017486572265625, 0.0272674560546875, -0.0155487060546875, -0.032958984375, 0.0291900634765625, -0.0648193359375, -0.0114898681640625, -0.03759765625, 0.0211181640625, 0.019195556640625, 0.007053375244140625, -0.005153656005859375, 0.01458740234375, -0.01317596435546875, -0.0294036865234375, -0.006134033203125, -0.016357421875, -0.0236358642578125, 0.002010345458984375, -0.0088043212890625, -0.0094146728515625, 0.018157958984375, -0.0262451171875, -0.0012493133544921875, -0.0328369140625, 0.02630615234375, -0.0312042236328125, 0.02606201171875, 0.0015697479248046875, 0.002704620361328125, -0.00691986083984375, 0.0110321044921875, -0.0026988983154296875, 0.0122222900390625, -0.0005235671997070312, -0.0134429931640625, 0.01290130615234375, 0.0030231475830078125, -0.002658843994140625, -0.0153045654296875, -0.0020351409912109375, 0.0181121826171875, 0.024078369140625, -0.021881103515625, -0.004665374755859375, 0.00995635986328125, 0.0271759033203125, -0.019287109375, -0.0202484130859375, 0.01947021484375, -0.004901885986328125, 0.035308837890625, -0.0126190185546875, -0.01422119140625, -0.02197265625, -0.0210113525390625, 0.0023441314697265625, -0.030731201171875, 0.008758544921875, 0.01287841796875, 0.0162200927734375, -0.024993896484375, -0.0289154052734375, 0.018463134765625, 0.0067596435546875, -0.0033893585205078125, -0.0284881591796875, -0.032379150390625, 0.0364990234375, 0.018341064453125, 0.038330078125, 0.0039825439453125, 0.0005970001220703125, 0.028961181640625, -0.032745361328125, -0.026153564453125, 0.0014314651489257812, -0.029083251953125, 0.0487060546875, 0.0196075439453125, 0.026519775390625, -0.00887298583984375, -0.003948211669921875, 0.00972747802734375, -0.0174560546875, 0.0009918212890625, -0.01470184326171875, 0.0025577545166015625, -0.00966644287109375, 0.0238494873046875, 0.0258941650390625, 0.07537841796875, -0.0230560302734375, 0.0200653076171875, 0.00556182861328125, -0.028717041015625, 0.006458282470703125, -0.005420684814453125, -0.00701904296875, 0.00394439697265625, 0.007076263427734375, 0.0384521484375, 0.0033969879150390625, 0.0205535888671875, -0.03118896484375, -0.0142669677734375, 0.01201629638671875, 0.0287322998046875, -0.01055145263671875, 0.028167724609375, -0.01132965087890625, 0.0299072265625, -0.01561737060546875, 0.0306549072265625, 0.0135345458984375, -0.0411376953125, -0.039215087890625, 0.01006317138671875, -0.0007371902465820312, 0.0125274658203125, -0.046630859375, -0.0205230712890625, -0.04510498046875, 0.027587890625, 0.00374603271484375, 0.009124755859375, 0.017181396484375, -0.006145477294921875, -0.0117645263671875, -0.03900146484375, -0.0133056640625, 0.03326416015625, 0.01953125, -0.04034423828125, 0.0005259513854980469, -0.0005497932434082031, -0.00444793701171875, 0.0163726806640625, -0.0268096923828125, -0.0012416839599609375, 0.02252197265625, -0.031463623046875, 0.0156402587890625, 0.0312042236328125, -0.0472412109375, 0.006435394287109375, 0.00446319580078125, -0.03228759765625, 0.029266357421875, 0.01299285888671875, 0.0234832763671875, -0.048736572265625, -0.010284423828125, 0.033294677734375, -0.0002598762512207031, -0.0081787109375, -0.0009889602661132812, -0.0015478134155273438, 0.03375244140625, -0.00794219970703125, 0.033477783203125, -0.00811004638671875, 0.0232391357421875, -0.0189208984375, 0.042999267578125, -0.00644683837890625, 0.02850341796875, -0.02459716796875, -0.011444091796875, -0.044769287109375, 0.0169525146484375, 0.00569915771484375, 0.00881195068359375, 0.051666259765625, -0.00646209716796875, -0.0014467239379882812, 0.01190948486328125, -0.03070068359375, 0.005828857421875, 0.0246429443359375, -0.0164947509765625, -0.0241851806640625, 0.058563232421875, 0.031646728515625, 0.0005884170532226562, -0.000644683837890625, -0.037445068359375, 0.011077880859375, -0.018646240234375, -0.01044464111328125, 0.0136260986328125, 0.05718994140625, -0.024871826171875, 0.0269927978515625, 0.022552490234375, 0.0219879150390625, 0.0312042236328125, -0.033111572265625, -0.002948760986328125, -0.01505279541015625, -0.007602691650390625, -0.01155853271484375, 0.0469970703125, 0.0372314453125, -0

In [29]:
qdrant_client.upsert(
    collection_name="Amazon-items-collection-01-hybrid-search",
    points=pointstructs[0:500],
    wait=True
)

UpdateResult(operation_id=3, status=<UpdateStatus.COMPLETED: 'completed'>)

In [30]:
qdrant_client.upsert(
    collection_name="Amazon-items-collection-01-hybrid-search",
    points=pointstructs[500:],
    wait=True
)

UpdateResult(operation_id=4, status=<UpdateStatus.COMPLETED: 'completed'>)

### Hybrid Retrieval

In [31]:
def retrieve_data(query, k=5):

    query_embedding = get_embedding(query)

    results = qdrant_client.query_points(
        collection_name="Amazon-items-collection-01-hybrid-search",
        prefetch=[
            Prefetch(
                query=query_embedding,
                using="text-embedding-3-small",
                limit=20
            ),
            Prefetch(
                query=Document(
                    text=query,
                    model="qdrant/bm25"
                ),
                using="bm25",
                limit=20
            )
        ],
        query=FusionQuery(fusion="rrf"),
        limit=k
    )

    retrieved_context_ids = []
    retrieved_context = []
    similarity_scores = []
    retrieved_context_ratings = []

    for result in results.points:
        retrieved_context_ids.append(result.payload["parent_asin"])
        retrieved_context.append(result.payload["preprocessed_description"])
        similarity_scores.append(result.score)
        retrieved_context_ratings.append(result.payload["average_rating"])

    return {
        "retrieved_context_ids": retrieved_context_ids,
        "retrieved_context": retrieved_context,
        "similarity_scores": similarity_scores,
        "retrieved_context_ratings": retrieved_context_ratings
    }

In [32]:
results = retrieve_data("Can I get a tablet?", k=20)

In [33]:
results

{'retrieved_context_ids': ['B0BN58Z4YX',
  'B0B157WDDJ',
  'B0BSD3QK7M',
  'B09RHF4L45',
  'B0B159KDFP',
  'B0BHVH4D37',
  'B0B58CPFWY',
  'B0C7DCS2KW',
  'B0BCFYCXRH',
  'B0B6ZZH83Y',
  'B0BGHBL86V',
  'B09WR36NK8',
  'B0BT83RRJ2',
  'B0BWRZ1HRD',
  'B09XQMRYBJ',
  'B09SZNLXJQ',
  'B0B2KJKT86',
  'B07Y36DDYM',
  'B0BZCM9CBR',
  'B09RN3KN5C'],
 'retrieved_context': ['ASWINN Tablet Tripod Stand, Gooseneck 65" Height Adjustable Tablet Stand Floor with 360° Rotating Tripod Mount Suitable for iPhone,Tablet,Kindle and All 4.5-12.9 Inch Tablet and Phone (Black) 【Free Your Hands】: With this gooseneck arm tablet tripod stand, you can find a more comfortable way to use tablet & Phone in bed or sofa in winter. Release your hands while make your leisure time more enjoyable，the best Christmas gift or New Year gifts for wife,husband,elders,friend or colleague. 【Versatile Gooseneck Tablet Tripod Stand】This ergonomic gooseneck tablet holder suits most tablets and phones. you can easily get your desired angle to meet your needs at different angles and positions. Except for watching movies, you are also allowed to use your tablet for visual presentations, like reading sheet music, watching videos, zoom calls, online teaching, public speaking, reading e-books, giving performances, etc. 【Wide Compatibility】It suitable for various tablets and mobile devices ranging from 4.5 to 12.9 inches. For smartphones like iPhone7, 7plus, 8, 8plus, x, XR, xs, xs max, iPhone 11, 12, 13,14 series.Galaxy Tab,Fire 7, Fire HD 8, Fire HD 10, N- Switch and etc. 【360 degree rotation and height adjustable】 - The tablet holder can be rotated 360 degree, making it easy to switch your tablet from portrait mode to landscape mode. Equipped with height adjustment function from 27 to 65 inch, makes this tablet floor stand easy to suit all of your viewing postures, such as lying, sitting, standing and so on. 【Strong Stability】Sturdy tripod base makes the stand more stable and reliable. Made by premium aluminum alloy, the gooseneck arm and extension tube are more durable than usual. ASWINN tablet floor stand provides safe and secure support for your device. 【Three Year Warranty】If there are some missing parts when you receive the product, please contact us directly for replacement. We provide high quality service,if you don\'t love it, you can get a full refund,total risk-free purchase,we provide three year warranty.',
  "G-TiDE Kids Tablet, 7 inch Tablet for Kids, 32GB+2GB Kids Learning Tablet, 5MP Dual Camera HD, Parental Control App- KLAP, Toddler Tablet Case, WiFi Tablets Shoulder Straps, Pink 🤗【Explore More Fun on Klap】G-TiDE Klap kids tablet is designed for learning and playing. This tablet for kids offers various creative contents such as brain training, painting, gaming, kids TV, etc. Learning while playing is better for kids to know the world. With a 32GB bigger storage, which can be extended to 128GB (micro SD card not included), this kids tablet is perfect for children aged 3-7 years old. You could get more educational apps from Google Play Store (GMS). 🤗【Kids-proof Case & Eye-protection Screen】G-TiDE's exclusive kids tablet case is made of impact-resistant EVA material. When your kid is playing outdoors with the tablet or accidentally dropping the tablet on the ground at home, it protects the kids tablet from bumps and minor drops. This kids tablet comes with an adjustable shoulder strap, so your little one can take their tablet wherever they go. With a 270° adjustable stand, you can place it at the distance that suits your kids best. 🤗【Amazing Experience on Klap Kids Tablet】G-TiDE Klap kids tablet offers an amazing experience with its learning & playing App - Klap. This app offers various creative content such as brain training, painting, gaming, kids TV etc. Learning while playing is better for kids to gain more knowledge. When there are more children, they can also watch kid's TV and play two-player games, they can also learn from each other. This kids tablet is perfect for children aged 3-7 years old and has a storage capacity of 32GB, which can be expanded up to 128GB(micro SD card not included). You can download more apps from Google Play Store, like YouTube Kids, Netflix, and other popular apps for kids tablets. 🤗【Easy Parental Controls】KLAP has parental controls that allow you to create over 20 different children's accounts and customize learning content and time limits according to their individual needs. It also includes features such as a child lock, remote video control, content filtering, a one-button lock screen, and alarm setting to ensure your children can safely browse websites. When you're busy working and don't have time to supervise your children, you can set content and time limits for them to play. 🎁【Perfect Gift For Kids】G-TiDE S1 provides endless online age-appropriate content, ensuring safe browsing for kids aged 3-7 years old. It offers an easy and fun way for kids to learn and play. This makes it the perfect gift for your child for Christmas and birthdays. We offer a 12-month worry-free guarantee, and you can find our official mailbox on the package's back for any service-related inquiries. Please don't hesitate to contact us if you have any questions about our tablets. G-TiDE is always by your side.",
  'ZZB Tablet 10 Inch Android 11 Tablets, 64GB+4GB Tablet, 512GB Expand，6000mah Battery, Quad-Core Processor Tableta, 8MP Camera WiFi BT 10.1\'\' IPS HD Touch Screen,10 in Tabletas. 【High-performance gaming tablet】 The ZZB 10.1“ tablet has a high performance 64-bit 1.8GHZ CPU( unlike most other tablets on the market with 1.3GHZ CPU), and 4GB RAM, which is 200% better than other tablets with 2GB RAM. you can really feel smooth running and higher performance. Perfect for watching videos, learning tools, reading e-books, work and games. 【WIFI and 5.0BT 】 ZZB WIFI tablet supports WIFI network and 5.0BT, enjoy faster and more stable download and Internet surfing, achieve faster transmission, complete more work in less time, let you no longer have boring waiting. 【Android 11 Tablet GMS Certification Complete】 ZZB\'s latest tablet uses Android 11.0, which is loaded with the latest features. Various features have been enhanced, so you can operate more lightly and enjoy the latest experience of Android 11. With certification of Google Mobile Service (GMS) and pre-installed Google Play supports Facebook, Twitter, YouTube, Tiktok, Line, Instagram and other trendy social apps, Support Microsoft Office Software. 【10.1" IPS Display & Dual Camera】The high clear tablet, with dual camera (8 megapixel rear, 2 megapixel front), can take beautiful photos and video conversations, stylish appearance, and elegant packaging, is the best choice for gifts. 10.1IN HD tablet equipped with high resolutionof 10.1-inch 1280*800 IPS display. Sizing up to 10.1 inches, you get more space, best choice for movie and video viewing and site browsing. 【512GB Memory & Large Capacity Battery】 The 64GB Tablet comes with 64 GB of built-in storage and up to 512GB of expandable microSD card storage for even more space. In addition, the built-in 6000mah battery can be used for a long time. You can download many movies, e-books and music. A single charge of the battery can last up to 12 hours which makes it an attractive tablet.',
  'plimpton Android Tablet 10 inch - 8 Core Processor, 4GB RAM 64GB Storage, 1.8M Length USB-C Cable, Android 11, 1920 x 1200 FHD IPS, 13MP Sony Rear Camera, 6000mAh Battery, 2.4G+5G WiFi Tablets PC High Performance Tablet 10.1 inch: Features a faster 1.8GHz Octa-Core CPU and 4GB RAM, you can not only obtain seamless multitasking and hyper-fast content streaming experience, but also can view social media, watch videos, play games, complete homework or finish work. With a 64GB internal storage and support a SD card expanded to 512GB(NOT included), no longer worry about insufficient memory.★★Please note this is a Wi-Fi tablet, not compatible with SIM card 2022 Latest Android 11 Tablets: Equipped with the latest Android 11 system (GMS certified). Automatic subtitleing, smart reply, notification "bubble", dark theme, eye protection mode etc. It also launches apps 20% faster than Android 10 OS. New control spaces and more privacy features allow you to create a rich user central expression. You can enjoy installing apps such as Netflix, Tik Tok, YouTube, Twitter from the Google Play Store. It is a good tablet for kids and adult Metal Body & 1080p Full HD Screen: Plimpton 10 inch android tablet uses a slim metal body, and the 2.5D touchscreen display in a good-look will be a better for using and will not be easily scratched. 1920 x 1200 Full HD IPS screen with a wide viewing angle that brings you vivid display image. Easily enjoy immersive reading on the large-screen display, and switch to eye comfort mode when read at night. ★★Since the LCD screen is fragile, we recommended to use it with P50 tablet screen protector Multi-function Google Tablet: Easily connect this tablet to the docking keyboard (sold separately), and get the ultimate experience of tablet and laptop anytime, anywhere. Enjoy the use of 2.4G/5G WIFI frequency band and Bluetooth 5.0, with stronger signal and higher speed. A 180 cm USB-C cable made distance charging more convenience. Screen cast is supported. Project your tablet to a big TV screen wirelessly when needed. ★★If your tablet has problems with WiFi, please contact us at any time Dual Camera & Long Battery Life: Tablet 10 inch Android 11 equipped with front 5MP & rear 13MP dual cameras, you can capture and share those special moments with your friends and family in your life. Built-in 6000mAh battery, your entertainment will last up to 7-10 hours.(The battery life varies based on device settings and usage etc. Certain apps may reduce battery life) ★★Plimpton Tablets come with 1 year free replacement and lifetime warranty, please don\'t hesitate to get in touch with us',
  "G-TiDE Kids Tablet, 7 inch Tablet for Kids, 32GB+2GB Kids Learning Tablet, 5MP Dual Camera HD, Parental Control App- KLAP, Toddler Tablet Case, WiFi Tablets Shoulder Straps, Blue 💙 【Explore More Fun on Klap】G-TiDE Klap kids tablet is designed for learning and playing. This tablet for kids offers various creative contents such as brain training, painting, gaming, kids TV, etc. Learning while playing is better for kids to know the world. With a 32GB bigger storage, which can be extended to 128GB (micro SD card not included), this kids tablet is perfect for children aged 3-7 years old. You could get more educational apps from Google Play Store (GMS). 💙 【Kids-proof Case & Eye-protection Screen】G-TiDE's exclusive kids tablet case is made of impact-resistant EVA material. When your kid is playing outdoors with the tablet or accidentally dropping the tablet on the ground at home, it protects the kids tablet from bumps and minor drops. This kids tablet comes with an adjustable shoulder strap, so your little one can take their tablet wherever they go. With a 270° adjustable stand, you can place it at the distance that suits your kids best. 💙 【Amazing Experience on Klap Kids Tablet】G-TiDE Klap kids tablet offers an amazing experience with its learning & playing App - Klap. This app offers various creative content such as brain training, painting, gaming, kids TV etc. Learning while playing is better for kids to gain more knowledge. When there are more children, they can also watch kid's TV and play two-player games, they can also learn from each other. This kids tablet is perfect for children aged 3-7 years old and has a storage capacity of 32GB, which can be expanded up to 128GB(micro SD card not included). You can download more apps from Google Play Store, like YouTube Kids, Netflix, and other popular apps for kids tablets. 💙 【Easy Parental Controls】KLAP has parental controls that allow you to create over 20 different children's accounts and customize learning content and time limits according to their individual needs. It also includes features such as a child lock, remote video control, content filtering, a one-button lock screen, and alarm setting to ensure your children can safely browse websites. When you're busy working and don't have time to supervise your children, you can set content and time limits for them to play. 🎁【Perfect Gift For Kids】G-TiDE S1 provides endless online age-appropriate content, ensuring safe browsing for kids aged 3-7 years old. It offers an easy and fun way for kids to learn and play. This makes it the perfect gift for your child for Christmas and birthdays. We offer a 12-month worry-free guarantee, and you can find our official mailbox on the package's back for any service-related inquiries. Please don't hesitate to contact us if you have any questions about our tablets. G-TiDE is always by your side.",
  "7 inch Tablet, Android 11, 2GB RAM 32GB ROM, Quad-Core Processor, Dual Camera, WiFi, Bluetooth, 128GB Expand, Google Play GMS Certified 【Android 11, 2GB RAM+32GB ROM】 7 inch tablet use the latest Android 11.0 OS, 2GB RAM+32GB ROM, Can be expanded up to 512GB via TF card, ensures you have an ultra-smooth gaming and speedy multimedia using experience, delivering quick app launches 【Google GMS Certified】 The android tablet has passed the GMS certification and Pre-installed Google Play, You have full access to the latest Google service, such as Google Play, WhatsApp, G-mail, Skype, Disney+, Netflix, Twitter, YouTube, Tiktok, Google Assistant and more brilliant apps 【3000mAh Ultra-large battery】This 7 inch Android Tablet equipped with 3000 mAh battery with a 1024 x 600 brilliant HD IPS display, can provides more than 6 hours of mixed-use, It's ready for daily life as well as travel 【Dual Camera & Bluetooth】Tablet with dual camera, Flash Light, Support Bluetooth, WIFI, 32GB Storage, 1080P Videos. Meets Reading, Photograph, videos, Music, etc. Suitable for Most Life Scenarios 【Ideal Gift and Service Guarantee】 RliyOliy tablet is the ideal gift for your kids and friends, it is also a learning tablet for kids and an easy to operate tablet for older people We guarantee quality. If you have any questions, please contact us, our customer service representative will get back to you within 24 hours.",
  'MoKo Case Fit with Amazon All-New Kindle Fire 7 Tablet (2022 Release-12th Generation) Latest Model 7", Perfect Protection with Fully Covered Soft TPU Edge Clear Back Cover for DIY, Indigo ⭐【Good Compatibility】Designed exclusively for Amazon All-New Kindle Fire 7 Tablet (2022 Release-12th Generation) Latest Model 7. Not fit other prior generation Kindle devices. ⭐【Superior Material】With four all-round soft TPU edge, this tablet protector will provide a solid protection of shock absorption to your precious Kindle Fire 7 Tablet 2022 devices. ⭐【Extra Pertection】Beyond the protection of soft edge, the covered four angle of airbag will further ensure the safety of your devices, offering a all-round protection when encountering accidental falling. ⭐【Accurate Cutouts】The precise cutouts for the ports grants you much convenience. Access to all the controlls and features. ⭐【DIY Your Unique Pattern】The clear shape of this tablet case offers you a DIY chance. You can stick some stickers or decals on you tablet, be free to express your individuality. Easy to get it on or remove, also convenient to clean.',
  'KYASTER Kids Tablet, 7 inch 5G WiFi 6 Android 12 Tablet for Kids, Full HD 1920x1200 IPS Screen, 2GB RAM 32GB ROM,Parental Controls Game Education Apps,EVA Kids-Proof Case with Stylus 💗【Full HD 1920*1200 IPS Touch Screen】 7 inch IPS touch screen with native 1080p resolution display,178° wide view angle,Clear bright screen provides outstanding visual experience,323 PPI and high-contrast ratio makes details pop,a good childrens tablet to enjoy learning, gaming,with eyes protection for your babies. 💗【Pre-installed Kids App with Parental Control】 COPPA-certified apps for children education and entertainment. the simple advanced parental control mode, with screen time setting, app filter and surfing content management,always keep your child safe without constant supervision.you can also install other apps like YouTube Kids, Netflix, Hulu from google play store. 💗【High-End Configuration & Android 12 Go OS】 This kids tablets is equipped with the latest version of GMS-certified Android 12.0 Go operating system, which is safer and faster than the old version and has an ad-blocking feature. The 1.8 GHz quad-core processor is 20% faster than normal processors on the basic frequency.5G wifi6 is three times faster than 2.4G wifi5. 💗【Light EVA case & Professional Stylus】 The baby food-grade kids-proof EVA case with great resilience is designed to prevent the tablet from damage during falls and collisions,a perfect toddler tablet,durable and firm.The 90-degree adjustable stand enables kids to get excellent viewing experience from all angles. The professional stylus with metal fiber penpoint can be easy placed into the pen tray of the case. 💗【Great Kids Gift & 5-star Services】 This 7" full-featured tablet for boys & girls is a good friend for educational,it includes 2mp+5mp cameras with flash,the 3,200mAh battery ensures 8-hours of mixed use on a single charge. 2gb ddr+32gb harddisk,with external up to 128 GB micro SD card storage (card not included). If you have any other questions, please contact us to ensure your 100% satisfaction.',

### Hybrid Search with weighted RRF

In [34]:
def retrieve_data(query, k=5):

    query_embedding = get_embedding(query)

    results = qdrant_client.query_points(
        collection_name="Amazon-items-collection-01-hybrid-search",
        prefetch=[
            Prefetch(
                query=query_embedding,
                using="text-embedding-3-small",
                limit=20
            ),
            Prefetch(
                query=Document(
                    text=query,
                    model="qdrant/bm25"
                ),
                using="bm25",
                limit=20
            )
        ],
        query=models.RrfQuery(rrf=models.Rrf(weights=[3,1])),
        limit=k
    )

    retrieved_context_ids = []
    retrieved_context = []
    similarity_scores = []
    retrieved_context_ratings = []

    for result in results.points:
        retrieved_context_ids.append(result.payload["parent_asin"])
        retrieved_context.append(result.payload["preprocessed_description"])
        similarity_scores.append(result.score)
        retrieved_context_ratings.append(result.payload["average_rating"])

    return {
        "retrieved_context_ids": retrieved_context_ids,
        "retrieved_context": retrieved_context,
        "similarity_scores": similarity_scores,
        "retrieved_context_ratings": retrieved_context_ratings
    }

In [35]:
results = retrieve_data("Can I get a tablet?", k=20)

In [36]:
results

{'retrieved_context_ids': ['B0B157WDDJ',
  'B0BN58Z4YX',
  'B0BSD3QK7M',
  'B0B159KDFP',
  'B09RHF4L45',
  'B0BGHBL86V',
  'B0BHVH4D37',
  'B0C7DCS2KW',
  'B09WR36NK8',
  'B0BCFYCXRH',
  'B0BT83RRJ2',
  'B0B58CPFWY',
  'B0BWRZ1HRD',
  'B0B6ZZH83Y',
  'B07Y36DDYM',
  'B09RN3KN5C',
  'B0BNKF9J6J',
  'B0B96TTN6T',
  'B08SC3C9MC',
  'B09PYV6B4B'],
 'retrieved_context': ["G-TiDE Kids Tablet, 7 inch Tablet for Kids, 32GB+2GB Kids Learning Tablet, 5MP Dual Camera HD, Parental Control App- KLAP, Toddler Tablet Case, WiFi Tablets Shoulder Straps, Pink 🤗【Explore More Fun on Klap】G-TiDE Klap kids tablet is designed for learning and playing. This tablet for kids offers various creative contents such as brain training, painting, gaming, kids TV, etc. Learning while playing is better for kids to know the world. With a 32GB bigger storage, which can be extended to 128GB (micro SD card not included), this kids tablet is perfect for children aged 3-7 years old. You could get more educational apps from Google Play Store (GMS). 🤗【Kids-proof Case & Eye-protection Screen】G-TiDE's exclusive kids tablet case is made of impact-resistant EVA material. When your kid is playing outdoors with the tablet or accidentally dropping the tablet on the ground at home, it protects the kids tablet from bumps and minor drops. This kids tablet comes with an adjustable shoulder strap, so your little one can take their tablet wherever they go. With a 270° adjustable stand, you can place it at the distance that suits your kids best. 🤗【Amazing Experience on Klap Kids Tablet】G-TiDE Klap kids tablet offers an amazing experience with its learning & playing App - Klap. This app offers various creative content such as brain training, painting, gaming, kids TV etc. Learning while playing is better for kids to gain more knowledge. When there are more children, they can also watch kid's TV and play two-player games, they can also learn from each other. This kids tablet is perfect for children aged 3-7 years old and has a storage capacity of 32GB, which can be expanded up to 128GB(micro SD card not included). You can download more apps from Google Play Store, like YouTube Kids, Netflix, and other popular apps for kids tablets. 🤗【Easy Parental Controls】KLAP has parental controls that allow you to create over 20 different children's accounts and customize learning content and time limits according to their individual needs. It also includes features such as a child lock, remote video control, content filtering, a one-button lock screen, and alarm setting to ensure your children can safely browse websites. When you're busy working and don't have time to supervise your children, you can set content and time limits for them to play. 🎁【Perfect Gift For Kids】G-TiDE S1 provides endless online age-appropriate content, ensuring safe browsing for kids aged 3-7 years old. It offers an easy and fun way for kids to learn and play. This makes it the perfect gift for your child for Christmas and birthdays. We offer a 12-month worry-free guarantee, and you can find our official mailbox on the package's back for any service-related inquiries. Please don't hesitate to contact us if you have any questions about our tablets. G-TiDE is always by your side.",
  'ASWINN Tablet Tripod Stand, Gooseneck 65" Height Adjustable Tablet Stand Floor with 360° Rotating Tripod Mount Suitable for iPhone,Tablet,Kindle and All 4.5-12.9 Inch Tablet and Phone (Black) 【Free Your Hands】: With this gooseneck arm tablet tripod stand, you can find a more comfortable way to use tablet & Phone in bed or sofa in winter. Release your hands while make your leisure time more enjoyable，the best Christmas gift or New Year gifts for wife,husband,elders,friend or colleague. 【Versatile Gooseneck Tablet Tripod Stand】This ergonomic gooseneck tablet holder suits most tablets and phones. you can easily get your desired angle to meet your needs at different angles and positions. Except for watching movies, you are also allowed to use your tablet for visual presentations, like reading sheet music, watching videos, zoom calls, online teaching, public speaking, reading e-books, giving performances, etc. 【Wide Compatibility】It suitable for various tablets and mobile devices ranging from 4.5 to 12.9 inches. For smartphones like iPhone7, 7plus, 8, 8plus, x, XR, xs, xs max, iPhone 11, 12, 13,14 series.Galaxy Tab,Fire 7, Fire HD 8, Fire HD 10, N- Switch and etc. 【360 degree rotation and height adjustable】 - The tablet holder can be rotated 360 degree, making it easy to switch your tablet from portrait mode to landscape mode. Equipped with height adjustment function from 27 to 65 inch, makes this tablet floor stand easy to suit all of your viewing postures, such as lying, sitting, standing and so on. 【Strong Stability】Sturdy tripod base makes the stand more stable and reliable. Made by premium aluminum alloy, the gooseneck arm and extension tube are more durable than usual. ASWINN tablet floor stand provides safe and secure support for your device. 【Three Year Warranty】If there are some missing parts when you receive the product, please contact us directly for replacement. We provide high quality service,if you don\'t love it, you can get a full refund,total risk-free purchase,we provide three year warranty.',
  'ZZB Tablet 10 Inch Android 11 Tablets, 64GB+4GB Tablet, 512GB Expand，6000mah Battery, Quad-Core Processor Tableta, 8MP Camera WiFi BT 10.1\'\' IPS HD Touch Screen,10 in Tabletas. 【High-performance gaming tablet】 The ZZB 10.1“ tablet has a high performance 64-bit 1.8GHZ CPU( unlike most other tablets on the market with 1.3GHZ CPU), and 4GB RAM, which is 200% better than other tablets with 2GB RAM. you can really feel smooth running and higher performance. Perfect for watching videos, learning tools, reading e-books, work and games. 【WIFI and 5.0BT 】 ZZB WIFI tablet supports WIFI network and 5.0BT, enjoy faster and more stable download and Internet surfing, achieve faster transmission, complete more work in less time, let you no longer have boring waiting. 【Android 11 Tablet GMS Certification Complete】 ZZB\'s latest tablet uses Android 11.0, which is loaded with the latest features. Various features have been enhanced, so you can operate more lightly and enjoy the latest experience of Android 11. With certification of Google Mobile Service (GMS) and pre-installed Google Play supports Facebook, Twitter, YouTube, Tiktok, Line, Instagram and other trendy social apps, Support Microsoft Office Software. 【10.1" IPS Display & Dual Camera】The high clear tablet, with dual camera (8 megapixel rear, 2 megapixel front), can take beautiful photos and video conversations, stylish appearance, and elegant packaging, is the best choice for gifts. 10.1IN HD tablet equipped with high resolutionof 10.1-inch 1280*800 IPS display. Sizing up to 10.1 inches, you get more space, best choice for movie and video viewing and site browsing. 【512GB Memory & Large Capacity Battery】 The 64GB Tablet comes with 64 GB of built-in storage and up to 512GB of expandable microSD card storage for even more space. In addition, the built-in 6000mah battery can be used for a long time. You can download many movies, e-books and music. A single charge of the battery can last up to 12 hours which makes it an attractive tablet.',
  "G-TiDE Kids Tablet, 7 inch Tablet for Kids, 32GB+2GB Kids Learning Tablet, 5MP Dual Camera HD, Parental Control App- KLAP, Toddler Tablet Case, WiFi Tablets Shoulder Straps, Blue 💙 【Explore More Fun on Klap】G-TiDE Klap kids tablet is designed for learning and playing. This tablet for kids offers various creative contents such as brain training, painting, gaming, kids TV, etc. Learning while playing is better for kids to know the world. With a 32GB bigger storage, which can be extended to 128GB (micro SD card not included), this kids tablet is perfect for children aged 3-7 years old. You could get more educational apps from Google Play Store (GMS). 💙 【Kids-proof Case & Eye-protection Screen】G-TiDE's exclusive kids tablet case is made of impact-resistant EVA material. When your kid is playing outdoors with the tablet or accidentally dropping the tablet on the ground at home, it protects the kids tablet from bumps and minor drops. This kids tablet comes with an adjustable shoulder strap, so your little one can take their tablet wherever they go. With a 270° adjustable stand, you can place it at the distance that suits your kids best. 💙 【Amazing Experience on Klap Kids Tablet】G-TiDE Klap kids tablet offers an amazing experience with its learning & playing App - Klap. This app offers various creative content such as brain training, painting, gaming, kids TV etc. Learning while playing is better for kids to gain more knowledge. When there are more children, they can also watch kid's TV and play two-player games, they can also learn from each other. This kids tablet is perfect for children aged 3-7 years old and has a storage capacity of 32GB, which can be expanded up to 128GB(micro SD card not included). You can download more apps from Google Play Store, like YouTube Kids, Netflix, and other popular apps for kids tablets. 💙 【Easy Parental Controls】KLAP has parental controls that allow you to create over 20 different children's accounts and customize learning content and time limits according to their individual needs. It also includes features such as a child lock, remote video control, content filtering, a one-button lock screen, and alarm setting to ensure your children can safely browse websites. When you're busy working and don't have time to supervise your children, you can set content and time limits for them to play. 🎁【Perfect Gift For Kids】G-TiDE S1 provides endless online age-appropriate content, ensuring safe browsing for kids aged 3-7 years old. It offers an easy and fun way for kids to learn and play. This makes it the perfect gift for your child for Christmas and birthdays. We offer a 12-month worry-free guarantee, and you can find our official mailbox on the package's back for any service-related inquiries. Please don't hesitate to contact us if you have any questions about our tablets. G-TiDE is always by your side.",
  'plimpton Android Tablet 10 inch - 8 Core Processor, 4GB RAM 64GB Storage, 1.8M Length USB-C Cable, Android 11, 1920 x 1200 FHD IPS, 13MP Sony Rear Camera, 6000mAh Battery, 2.4G+5G WiFi Tablets PC High Performance Tablet 10.1 inch: Features a faster 1.8GHz Octa-Core CPU and 4GB RAM, you can not only obtain seamless multitasking and hyper-fast content streaming experience, but also can view social media, watch videos, play games, complete homework or finish work. With a 64GB internal storage and support a SD card expanded to 512GB(NOT included), no longer worry about insufficient memory.★★Please note this is a Wi-Fi tablet, not compatible with SIM card 2022 Latest Android 11 Tablets: Equipped with the latest Android 11 system (GMS certified). Automatic subtitleing, smart reply, notification "bubble", dark theme, eye protection mode etc. It also launches apps 20% faster than Android 10 OS. New control spaces and more privacy features allow you to create a rich user central expression. You can enjoy installing apps such as Netflix, Tik Tok, YouTube, Twitter from the Google Play Store. It is a good tablet for kids and adult Metal Body & 1080p Full HD Screen: Plimpton 10 inch android tablet uses a slim metal body, and the 2.5D touchscreen display in a good-look will be a better for using and will not be easily scratched. 1920 x 1200 Full HD IPS screen with a wide viewing angle that brings you vivid display image. Easily enjoy immersive reading on the large-screen display, and switch to eye comfort mode when read at night. ★★Since the LCD screen is fragile, we recommended to use it with P50 tablet screen protector Multi-function Google Tablet: Easily connect this tablet to the docking keyboard (sold separately), and get the ultimate experience of tablet and laptop anytime, anywhere. Enjoy the use of 2.4G/5G WIFI frequency band and Bluetooth 5.0, with stronger signal and higher speed. A 180 cm USB-C cable made distance charging more convenience. Screen cast is supported. Project your tablet to a big TV screen wirelessly when needed. ★★If your tablet has problems with WiFi, please contact us at any time Dual Camera & Long Battery Life: Tablet 10 inch Android 11 equipped with front 5MP & rear 13MP dual cameras, you can capture and share those special moments with your friends and family in your life. Built-in 6000mAh battery, your entertainment will last up to 7-10 hours.(The battery life varies based on device settings and usage etc. Certain apps may reduce battery life) ★★Plimpton Tablets come with 1 year free replacement and lifetime warranty, please don\'t hesitate to get in touch with us',
  "Kids Tablet 7 inch Android Toddler Tablet for Kids Learning APP Preinstalled 1GB RAM+32GB ROM 256GB Expand Support, 2MP Rear Camera Children’s Education Tablet Google Play YouTube Netflix ages 3 to 14 【Tablet Manufacture Moonka Kids tablet 7 inch】Equipped with the latest Android 10 system and 1.4Ghz quad-core processor (Multiple applications will run smoothly). 1240*600 HD touch screen, Bluetooth 4.0, stable WiFi, built-in 1GB RAM and 32GB ROM(support TF/microSD card, expand to at least 256GB) 0.3 front + 2.0 MP rear dual camera. 【Kids Friendly Designs】178-degree wide viewing angle IPS, vivid colors, light weight, grooved design, kids will be easy to hold. The special thickened silicone case has no odor and protects the tablet from bumps and drops. And the screen protector keeps your screen safe. The screen is evenly lit and the eyes are not tired. 175° adjustable stand frees hands. 【Pre-Installed Learning App】Pre-installed iWawa fun educational software to ensure access healthy websites and entertainment apps, including Kindle app, YouTube, Amazon Prime Video, Xfinity Stream, Movies, Music. Support at least 38 languages, including Spanish, GMS certified, full access to the latest Google Play Store, download the software you need, so Friendly to adults. 【Parental Control 】Parents are very easy to set this app for range of ages. Personalize the content touched, ensure browse age-appropriate websites, controlling screen time and setting a lock screen password to relax their eyes. 【Good Helper for you】Lots of Age-appropriate Apps, when you're planning a car trip, a plane ride, 3-14 year olds kids prefer a tablet to a phone. Best kids gift choice for Christmas, New Year, Easter and Birthday. Moonka Kids Tablet will be a good helper for you to manage your children.",
  "7 inch Tablet, Android 11, 2GB RAM 32GB ROM, Quad-Core Processor, Dual Camera, WiFi, Bluetooth, 128GB Expand, Google Play GMS Certified 【Android 11, 2GB RAM+32GB ROM】 7 inch tablet use the latest Android 11.0 OS, 2GB RAM+32GB ROM, Can be expanded up to 512GB via TF card, ensures you have an ultra-smooth gaming and speedy multimedia using experience, delivering quick app launches 【Google GMS Certified】 The android tablet has passed the GMS certification and Pre-installed Google Play, You have full access to the latest Google service, such as Google Play, WhatsApp, G-mail, Skype, Disney+, Netflix, Twitter, YouTube, Tiktok, Google Assistant and more brilliant apps 【3000mAh Ultra-large battery】This 7 inch Android Tablet equipped with 3000 mAh battery with a 1024 x 600 brilliant HD IPS display, can provides more than 6 hours of mixed-use, It's ready for daily life as well as travel 【Dual Camera & Bluetooth】Tablet with dual camera, Flash Light, Support Bluetooth, WIFI, 32GB Storage, 1080P Videos. Meets Reading, Photograph, videos, Music, etc. Suitable for Most Life Scenarios 【Ideal Gift and Service Guarantee】 RliyOliy tablet is the ideal gift for your kids and friends, it is also a learning tablet for kids and an easy to operate tablet for older people We guarantee quality. If you have any questions, please contact us, our customer service representative will get back to you within 24 hours.",
  'KYASTER Kids Tablet, 7 inch 5G WiFi 6 Android 12 Tablet for Kids, Full HD 1920x1200 IPS Screen, 2GB RAM 32GB ROM,Parental Controls Game Education Apps,EVA Kids-Proof Case with Stylus 💗【Full HD 1920*1200 IPS Touch Screen】 7 inch IPS touch screen with native 1080p resolution display,178° wide view angle,Clear bright screen provides outstanding visual experience,323 PPI and high-contrast ratio makes details pop,a good childrens tablet to enjoy learning, gaming,with eyes protection for your babies. 💗【Pre-installed Kids App with Parental Control】 COPPA-certified apps for children education and entertainment. the simple advanced parental control mode, with screen time setting, app filter and surfing content management,always keep your child safe without constant supervision.you can also install other apps like YouTube Kids, Netflix, Hulu from google play store. 💗【High-End Configuration & Android 12 Go OS】 This kids tablets is equipped with the latest version of GMS-certified Android 12.0 Go operating system, which is safer and faster than the old version and has an ad-blocking feature. The 1.8 GHz quad-core processor is 20% faster than normal processors on the basic frequency.5G wifi6 is three times faster than 2.4G wifi5. 💗【Light EVA case & Professional Stylus】 The baby food-grade kids-proof EVA case with great resilience is designed to prevent the tablet from damage during falls and collisions,a perfect toddler tablet,durable and firm.The 90-degree adjustable stand enables kids to get excellent viewing experience from all angles. The professional stylus with metal fiber penpoint can be easy placed into the pen tray of the case. 💗【Great Kids Gift & 5-star Services】 This 7" full-featured tablet for boys & girls is a good friend for educational,it includes 2mp+5mp cameras with flash,the 3,200mAh battery ensures 8-hours of mixed use on a single charge. 2gb ddr+32gb harddisk,with external up to 128 GB micro SD card storage (card not included). If you have any other questions, please contact us to ensure your 100% satisfaction.',
  'MERRYROYAL Tablet 10.4 inch 32GB Android 11 Quad Core 6000mAh 1332x800 HD CTP Tablets (LightGray) 💭【High-performance Tablet】Equipped with 2GB RAM, 32GB ROM, it is perfectly suited for everyday learning and entertainment use. Equipped microSD card slot allows expansion up to 128GB. 💭【Update Android 11 Go System】Runs the latest Android 11 GO with Google play store pre-installed and full access to all apps. Will boot up to 30% faster than Android 10. 💭【Slim Design】With its perfect curvature and ultra-narrow bezel slim design of only 8.9mm, the MERRYROYAL Android 11 tablet illustrates our pursuit of beauty and technology. 💭【 Long Battery Life 】MERRYROYAL tablet with a massive 6000mAh battery for up to 5 hours, the 10.4-inch tablet is a truly great companion for your leisure and entertainment. 💭【 After-sales service 】Offers 1 year return service. Comes with a USB Type-C data cable. To ensure the quality of our service, if you have any questions about our tablet, please contact us.',